client/rest/rest/src/db/dbUtils.js
client/rest/rest/test/db/dbFormattingRules_spec.js
client/rest/rest/test/db/dbUtils_spec.js
client/rest/rest/test/server/messageFormattingRules_spec.js

- All the addresses in the REST response are in decoded format. 
- Example `98E0D138EAF2AC342C015FF0B631EC3622E8AFFA04BFCC56`
- `Decoded` address format is not user-friendly. We have feedback from the community and discussion, change the address to encoded format.
- Example `TDQNCOHK6KWDILABL7YLMMPMGYRORL72AS74YVQ`
- Convert addresses from decoded to encoded (base32) format.
- updated unit test

Client/rest: convert to encoded address

---

.github/CODEOWNERS.md

See [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for more configuration options. We can also enforce per-language reviewers, but for now, I think it is saner to keep to subdirectories.

[monorepo] task: create CODEOWNERS.md to automatically assign reviewers

---

sdk/python/tests/core/facade/test_BatchOperations.py
sdk/python/tests/core/facade/test_NemFacade.py
sdk/python/tests/core/facade/test_SymbolFacade.py
sdk/python/tests/core/test_AccountDescriptorRepository.py
sdk/python/tests/core/test_BlockchainSettings.py
sdk/python/tests/core/test_NodeDescriptorRepository.py

problem:
- yaml does not support tab indent
- pycodestyle does not allow python tab indent and yaml space indent
solution:
- replace yaml tabs with spaces

test(sdk/python): fix tests with hardcoded yaml inputs after tabification

---

catbuffer/schemas/nem/multisig/multisig.cats
sdk/python/examples/descriptors/symbol_metadata.py
sdk/python/generator/printers.py
sdk/python/symbolchain/nc/__init__.py
sdk/python/symbolchain/sc/__init__.py

problem:
generator is currently serializing all integers as unsigned but
solution:
int* types should be serialized with signed=True
issue: #7

[sdk/python]: fix serialization of signed integers

---

client/catapult/docs/BUILD-docker.md
jenkins/catapult/runDockerBuild.py
jenkins/catapult/runDockerTests.py
jenkins/catapult/runDockerTestsInnerLint.py
jenkins/catapult/templates/RunBench.yaml
jenkins/catapult/templates/RunLint.yaml
jenkins/catapult/templates/RunTest.yaml

With the move to monorepo, the path for linters, scripts and code are in different folders.
Update the python scripts to now take a ``--source-path`` which points to where the catapult source is located.
Linters and scripts also have different mount points in the docker container.

fix: Update paths for docker build scripts

---

jenkins/shared-library/vars/createMonorepoMultibranchJobs.groovy
jenkins/shared-library/vars/createMultibranchJob.groovy
jenkins/shared-library/vars/monorepoSeedPipeline.groovy
linters/groovy/.groovylintrc.json
seed-job/Jenkinsfile
seed-job/buildConfiguration.yaml

Add the seed job which can be used to automatically create the other package jobs.
The seed job can be configured to update the package jobs if changes are made to the buildConfiguration.yaml file.
The ``buildConfiguration.yaml`` has layout of each package and their dependencies.

 feat: Add seed job for monorepo layout.

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

The first build with parameters on a multibranch job fails due to no parameters getting included.  Add a check for this condition to workaround the bug below.
https://issues.jenkins.io/browse/JENKINS-41929

[Jenkins] fix: First build failed with missing property

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

Added a check for the ``SHOULD_PUBLISH_IMAGE`` param which is null on the first build.

[Jenkins] fix: Add check for SHOULD_PUBLISH_IMAGE

---

client/rest/scripts/ci/setup_test.sh
jenkins/docker/javascript.Dockerfile

Rest tests that required MongoDB were failing due to MongoDB not available in the image.
Added MongoDB and start the process in the setup test staged.

[client/rest] fix: Add MongoDB to Dockerfile

---

sdk/python/symbolchain/nem/TransactionFactory.py
sdk/python/tests/nem/test_TransactionFactory.py

Right now cosignatures in nem can't be used, when transaction  is created via descriptors
Added processing of `Cosignature` and `SizePrefixedCosignature` in nem's TransactionFactory
Tested using upcoming PR, since this work the same as any other structs, separate unittests are not needed.

[sdk/python] allow descriptor-inlined cosignatures

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

Run the script file directly with bash.
The ``init.sh`` was found but failed to run.
The script was not found when executed directly by the shell.
The script will run with bash.

[monorepo] fix: init file not run.

---

sdk/javascript/Jenkinsfile
sdk/javascript/package.json
sdk/javascript/scripts/ci/test_vectors.sh

sdk js catbuffer vectors are not included in the code coverage resutls
code coverage is too low
updated pipeline to include catbuffer vectors for sdk js too
yes

[sdk/javascript]: include catvectors in code coverage

---

sdk/javascript/generator/StructTypeFormatter.py
sdk/javascript/src/nem/models.js
sdk/javascript/src/symbol/models.js
sdk/python/generator/EnumTypeFormatter.py
sdk/python/generator/FactoryFormatter.py
sdk/python/generator/PodTypeFormatter.py
sdk/python/generator/StructTypeFormatter.py
sdk/python/generator/printers.py
sdk/python/symbolchain/nc/__init__.py
sdk/python/symbolchain/sc/__init__.py

generated code is using `buffer_` instead of `buffer`
`buffer` is not a reserved word
replaced `buffer` with `buffer_`
yes

[sdk/python]: rename buffer_ to buffer

---

sdk/javascript/src/utils/arrayHelpers.js
sdk/javascript/test/utils/arrayHelpers_spec.js
sdk/python/symbolchain/ArrayHelpers.py
sdk/python/tests/test_ArrayHelpers.py

sdk/python ArrayHelpers is missing unit tests.
there are no unit tests.
mostly unified implementation with sdk/javascript and added unit tests.
yes

[sdk/python] task: add tests to ArrayHelpers and refactor to more closely match JS impl

---

catbuffer/schemas/symbol/block.cats
sdk/javascript/generator/printers.py
sdk/javascript/src/symbol/models.js
sdk/python/generator/printers.py
sdk/python/symbolchain/sc/__init__.py

* `@alignment` was missing on `block.transactions`
* besides that, wrong code was generated because only `is_byte_constrained` was handled correctly
* added missing attribute
* modified both js and py generator appropriately
* Manually verified that generated code seems fine and that only block handling has changed.

[sdk] fix block handling

---

catbuffer/parser/catparser/ast.py
catbuffer/parser/catparser/grammar/catbuffer.lark
catbuffer/parser/docs/cats_dsl.md
catbuffer/parser/tests/test_ast.py
catbuffer/schemas/symbol/block.cats
catbuffer/schemas/symbol/receipts.cats
catbuffer/schemas/symbol/transaction.cats

There is no way to indicate if a struct as aligned fields or not [ issue #101 ]
This prevents generators from making certain optimizations.
Added is_aligned struct attribute and applied it to schemas appropriately. 
yes

[catbuffer/parser] task: add struct is_aligned field

---

catbuffer/parser/CHANGELOG.md
catbuffer/parser/catparser/AstPostProcessor.py
catbuffer/parser/catparser/ast.py
catbuffer/parser/catparser/grammar/catbuffer.lark
catbuffer/parser/docs/cats_dsl.md
catbuffer/parser/tests/test_AstValidator.py
catbuffer/parser/tests/test_ast.py
catbuffer/schemas/symbol/block.cats

there is no way to specify padding of last element in an aligned array
within a block, the last transaction is NOT padded
within an aggregate, the last transaction is padded
add optional `[not] pad_last` qualifier to alignment attribute
yes

[catbuffer/parser]: extend alignment attribute to specify padding of last element

---

codecov.yaml

The current Rest Codecov flag is ``rest-gateway``
The Codecov flag used for Rest client is incorrect.
Rest client Codecov's flag name should be ``client-rest`` to match the package id.

[monorepo] fix: rest codecov flag name

---

sdk/javascript/generator/printers.py
sdk/javascript/src/nem/models.js
sdk/javascript/src/symbol/models.js
sdk/javascript/src/utils/arrayHelpers.js
sdk/javascript/test/utils/arrayHelpers_spec.js
sdk/python/generator/printers.py
sdk/python/symbolchain/ArrayHelpers.py
sdk/python/symbolchain/nc/__init__.py
sdk/python/symbolchain/sc/__init__.py
sdk/python/tests/test_ArrayHelpers.py

* Among other things #126 introduced bug 😬 
* #126 changed how sizes are calculated, but reading and writing still happened in padded version, so after adding block vectors, tests were obviously failing
* Added "exclude_last" flag in read/write variable in both SDKs
* using them in both generators
* on top of this simplified array size calculations inside generator (fixed accidental bug in the process)
* unittests added
* on top of that tested on newly created block vectors

[sdk] actually read/write block transactions properly

---

jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/findJenkinsfilePath.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/publish.groovy

Not able publish GitHub Pages from Jenkins
Symbol docs publishes to GitHub Pages to view the site.
The Symbol docs can use Jenkins to publish its content to GitHub Pages.

[jenkins] feat: add github pages publishing

---

jenkins/catapult/jenkins/catapult-client-build-base-image.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project.groovy
jenkins/catapult/jenkins/catapult-client-release-build.groovy
jenkins/catapult/runDockerTestsInnerTest.py

Catapult Jenkins job is using the old repo.
Catapult Jenkins job needs to be updated for the symbol repo
Catapult Jenkins jobs are run using the symbol repo
Yes by running the Jenkins jobs
https://jenkins.symboldev.com/job/Symbol/job/server-pipelines/job/catapult-client-build-catapult-project-daily/243/

[jenkins] fix: client catapult jobs

---

jenkins/docker/linter.Dockerfile

``sphinx-build: not found`` even after the package was installed.
The script not in the path
When installing sphinx, the errors below showed in the logs.
```
[2022-02-24T05:46:11.255Z]   WARNING: The scripts inv and invoke are installed in '/home/ubuntu/.local/bin' which is not on PATH.
[2022-02-24T05:46:11.255Z]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```
The sphinx package will be in the PATH variable.

[jenkins] fix: add .local/bin to path for python package

---

codecov.yaml

Client catapult has no code coverage data
Trying to upload code coverage data but the directory structure is not correct.
Updating the codecov.yaml file with client-catapult flag should resolve the problem.

[jenkins] fix: add client catapult flags

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

`CI` and `CD` are running in the same Docker container.
Docker build and publishing is failing due to `docker: not found` error since the `CD` is running in the docker container.
Moved the `dockerfile agent` definition to the `CI` pipeline stage, set it to reuse the same node and left the `CD` pipeline to work with the default agent instead of the container agent.

[jenkins] fix: cd pipeline agent is separated to support non-container agent

---

README.md

catapult/client coverage percentage is not in README
catapult/client coverage percentage is not in README
added coverage badge for catapult/client
N/A

[catapult/client] docs: include coverage in README

---

sdk/javascript/src/nem/TransactionFactory.js
sdk/javascript/src/symbol/TransactionFactory.js
sdk/javascript/test/nem/TransactionFactory_spec.js
sdk/javascript/test/symbol/TransactionFactory_spec.js

sdk javascript is outputting braces in JSON in duplicate
this is invalid JSON 
output only single brace(s)
yes

[sdk/javascript] fix: braces are being output in duplicate

---

jenkins/catapult/BasicBuildManager.py
jenkins/catapult/configuration.py
jenkins/catapult/configurations/gcc-10-code-coverage.yaml
jenkins/catapult/jenkins/catapult-client-build-catapult-project-daily.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project.groovy
jenkins/catapult/runDockerBuild.py
jenkins/catapult/runDockerBuildInnerBuild.py

There is no code coverage job for catapult client
Currently code coverage for the catapult client is generated manually.
created a daily code coverage job for the catapult client.
It is base on gcc 10 until update all the test images
Yes

[jenkins] feat: catapult code coverage job

---

jenkins/catapult/jenkins/catapult-client-build-catapult-project.groovy
jenkins/catapult/jenkins/catapult-client-prepare-base-image.groovy
jenkins/catapult/jenkins/catapult-client-release-build.groovy

There are two checkout for the release build.
1. Jenkins checkout into ``symbol-mono`` to get  the Jenkinfile.  This is configured in the Jenkins job.
2. The source checkout to do the build.
Usually these are the same but can be different like if repo is not the same.
The source is checkout in one folder but some of the scripts file was using another
Fix path to the where the source is checkout to be the same as the Jenkins job.
Cleanup the workspace also to make sure the correct source it used.
Yes

[jenkins] fix: use the same path for all checkout

---

client/catapult/docs/BUILD-manual.md
jenkins/catapult/installDepsLocal.py

The paths in the build steps does not match on the symbol repo.
Following the manual build steps failed as the path does not match.
Update the paths in the build steps to match the symbol repo.
Update the checkout protocol from git to https to fix the below
```
git clone -b release-1.10.0 git://github.com/google/googletest.git
Cloning into 'googletest'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
yes

[client/catapult] fix: manual build documentation

---

linters/python/lint_requirements.txt
sdk/javascript/generator/AbstractTypeFormatter.py
sdk/javascript/generator/EnumTypeFormatter.py
sdk/javascript/generator/FactoryFormatter.py
sdk/javascript/generator/PodTypeFormatter.py
sdk/python/generator/AbstractTypeFormatter.py
sdk/python/generator/EnumTypeFormatter.py
sdk/python/generator/FactoryFormatter.py
sdk/python/generator/PodTypeFormatter.py
sdk/python/tests/nem/test_NetworkTimestamp.py
sdk/python/tests/symbol/test_NetworkTimestamp.py
sdk/python/tests/symbol/test_TransactionFactory.py

pylint is currently an old version
upgraded pylint and fixed warnings
jenkins

[linters]: upgrade py linter to 2.13.4

---

.github/dependabot.yaml
.github/workflows/auto-merge.yaml

Dependabot PRs are manually merge into GitHub
Merge of PR is manual
Add a GitHub action which will auto merge all PRs from dependabot after the CI checks pass.
Note: commit-message prefix field is limited to 15 characters, monorepo was used in such case.
Tested the auto merge of Dependabot PR

[monorepo] feat: Auto-merge of dependabot prs

---

sdk/javascript/src/nem/NetworkTimestamp.js
sdk/javascript/src/symbol/NetworkTimestamp.js
sdk/javascript/test/nem/NetworkTimestamp_spec.js
sdk/javascript/test/symbol/NetworkTimestamp_spec.js

- It returns the wrong NetworkTimestamp, it should show Mar instead of Apr.
- In javascript Date's month is start from 0 (Jan), which is we need 2 (Mar) instead of 3 (Apr)

[sdk/javascript] fix: wrong epoch time

---

client/catapult/extensions/timesync/tests/ImportanceAwareNodeSelectorTests.cpp
client/catapult/tests/int/stress/CacheIntegrityTests.cpp
client/catapult/tools/addressgen/main.cpp

client/catapult fails to build with latest clang
variable set but not used warnings
fixed the warnings 
jenkins

[client/catapult] build: fix clang warnings

---

jenkins/docker/javascript.Dockerfile
jenkins/docker/python.Dockerfile
jenkins/shared-library/vars/codeCoverage.groovy

when codecov fails to upload code coverage data the Jenkins job is not failing. 
The latest codecov uploader tool have new parameters.
When codecov fails to upload coverage data it fails the Jenkins job.
Yes

[monorepo] fix: update codecov parameters

---

client/catapult/docs/BUILD-conan.md
client/catapult/docs/BUILD-manual.md

The repository paths in the Conan build steps does not match. There are also missing dependencies - for manual (`libgtest-dev`) and Conan (`pkg-config`) builds.
- Following the Conan build steps failed as the path does not match.
```
git clone https://github.com/symbol/catapult-client.git
```
- There is a missing dependency `pkg-config` for Linux Conan builds steps:
```
-- Looking for strlcpy - found
CMake Error at /opt/homebrew/Cellar/cmake/3.20.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```
- There is missing dependency `libgtest-dev` for Linux manual build steps:
```
> ninja
In file included from /root/build/symbol/client/catapult/tests/TestHarness.h:26,
from …
```

[client/catapult] fix: build documentation

---

jenkins/shared-library/vars/createMonorepoMultibranchJobs.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/monorepoSeedPipeline.groovy

When the build configuration file is updated all job are not run.
When the build configuration file is updated need to verify that all job still runs
Trigger all Jenkins jobs for the repo when the build configuration is updated.
Yes

[monorepo] fix: trigger all jobs on configuration change

---

jenkins/docker/java.Dockerfile

There is no java dockerfile for Jenkins
Unable to run to CI for Java projects
Add a Java docker file
Yes

[jenkins] task: add java dockerfile

---

.github/dependabot.yaml
linters/scripts/lint_last_commit.sh

Currently, there is no tag for dependabot pr.
Dependabot pr uses different tags on different projects.
All dependabot pr will use the dependency tag
Yes

[monorepo] fix: add dependency module

---

linters/git/.gitlint

Jenkins job fails if PR title is greater than 80
Some dependabot commit title are longer than 80 characters
Update the PR limit to 100

[monorepo] fix: increase pr title length

---

jenkins/docker/postgres.Dockerfile

Python apps that gets installed in local, are not in the default PATH.
Failed to run coverage python app
Add local bin to the PATH so local apps can be run.
Yes

[monorepo] fix: python local apps not in PATH

---

linters/scripts/lint_last_commit.sh

Each new repo setup in Jenkins, we are adding ``jenkins`` and/or ``monorepo`` to the modules
Does follow the DRY principle
add ``jenkins`` and ``monorepo`` to the common modules so future repo will not need to add these locally.
Yes, by running the ``lint_last_commit.sh`` script locally

[monorepo] fix: update common modules

---

sdk/javascript/src/index.js

problem: javascript doesn't have a standard way of converting hex string <=> Uint8Array.
the sdk has two functions that perform this conversion.
optin/reporting needed to reimplement them externally.
solution: export the functions so that they can be imported via
`const { hexToUint8, uint8ToHex } require('symbol-sdk').utils;`
issue: #215

[sdk/javascript]: expose 'hexToUint8' and 'uint8ToHex' from library

---

sdk/javascript/src/Network.js
sdk/javascript/src/nem/Network.js
sdk/javascript/src/symbol/Network.js
sdk/javascript/test/test/networkTests.js
sdk/python/symbolchain/Network.py
sdk/python/symbolchain/nem/Network.py
sdk/python/symbolchain/symbol/Network.py
sdk/python/tests/test/BasicNetworkTest.py
sdk/python/tests/test_Network.py

[sdk/javascript] task: add isValidAddressString to network classes
problem: there is no functionality to check if an address string is valid
the existing isValidAddress requires a typed Address, which implies a properly formed string
solution: add isValidAddressString to Network classes that accepts and validates string paramteter
issue: #214
[sdk/python] task: add is_valid_address_string to network classes
problem: there is no functionality to check if an address string is valid
the existing is_valid_address requires a typed Address, which implies a properly formed string
solution: add is_valid_address_string to Network classes that accepts and validates string paramteter
issue: #235

[sdk/*] add function for checking address string validity to sdks

---

client/rest/package-lock.json
client/rest/package.json
client/rest/src/catapult-sdk/model/address.js
client/rest/src/routes/MerkelTree.js

problem: js sdk has been upgraded to use noble for hashing but rest is still using js-sha3
solution: replace js-sha3 with noble

[rest] build: switch js-sha3 to noble

---

client/catapult/plugins/txes/mosaic/src/plugins/MosaicSupplyRevocationTransactionPlugin.cpp
client/catapult/plugins/txes/mosaic/tests/plugins/MosaicSupplyRevocationTransactionPluginTests.cpp

… 
problem: MosaicSupplyRevocationTransactionPlugin is not raising an AddressInteractionNotification that would link
the SourceAddress to the transaction as an affected account
solution: raise an AddressInteractionNotification with SourceAddress
issue: #108

[client/catapult]: MosaicSupplyRevocation SourceAddress is not linked as interacting address

---

sdk/javascript/examples/bip32_keypair.js
sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/examples/bip32_keypair.py
sdk/python/symbolchain/facade/NemFacade.py
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py

problem: BIP32_COIN_ID constant contains mainnet coin id.
This can be confusing when using testnet where a different coin id should be used.
solution: Drop BIP32_COIN_ID and replace it with a bip32Path function that returns a BIP32 path
given an account id.
issues: #241, #242

[sdk]: replace BIP32_COIN_ID constant with network-dependent bip32Path

---

sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/symbolchain/facade/NemFacade.py
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py

problem: facades look up well known networks by name, so custom networks cannot be used
solution: allow facades to be constructed around a network object in addition to a network name
issues: #245, #246

[sdk]: allow facades to be constructed around arbitrary network

---

README.md

Javascript SDK example link show not run
Javascript SDK example link was incorrect
1. Fix the Javascript SDK example link.
2. Add Javascript SDK build link
3. Add build and test link for Catapult Client
Yes, view the updated README

[monorepo] fix: readme job status links

---

client/rest/package-lock.json
client/rest/package.json
linters/python/lint_requirements.txt
sdk/javascript/package-lock.json
sdk/javascript/package.json

npm install failing
With the new npm release, npm updates are failing due to  mocha-jenkins-reporter only supports mocha 9.x
1. mocha-jenkins-reporter only supports mocha 9.x
- https://github.com/juhovh/mocha-jenkins-reporter/blob/34fe28ed6e12458a4263c77bd0ac5b6e011563b5/package.json#L26
2. Bump eslint from 8.16.0 to 8.17.0 in /sdk/javascript
3. Bump eslint from 8.16.0 to 8.17.0 in /client/rest
Yes, local in docker

[dependency] fix: mocha-jenkins-reporter only supports mocha 9.x

---

linters/python/.pylintrc
linters/python/lint_requirements.txt
sdk/python/scripts/ci/lint.sh
sdk/python/symbolchain/nem/external/ed25519.py

pylint 2.13.x does not report deprecated options
Starting with pylint  2.14 unknown options are reported and will fail if try to disable them
pylint 2.14.0 starts reporting options which has been removed.
1. ``no-self-use`` was moved an extension so load it.
https://pylint.pycqa.org/en/latest/whatsnew/2/2.14/summary.html#removed-checkers
2. The ``*-name-hint`` options were replaced with ``*-naming-style``.
The rgx options are still available, and they overrides the *-naming-style.
Thus removing ``*-name-hint`` options as they are not needed.
3. ``no-space-check`` option was removed in pylint 2.6 - https://pylint.pycqa.org/en/v2.11.1/whatsnew/2.6.html
4. ``misplaced-comparison-constant`` was moved to an extension but since this option was disabled so removed.
5. In python sdk exclude …

[linters] fix: pylint 2.14 reports unknown options

---

sdk/javascript/examples/descriptors/nem_namespace.js
sdk/javascript/generator/StructTypeFormatter.py
sdk/javascript/src/nem/TransactionFactory.js
sdk/javascript/src/nem/models.js
sdk/javascript/src/symbol/TransactionFactory.js
sdk/javascript/src/symbol/models.js
sdk/javascript/vectors/catbuffer.js
sdk/python/examples/descriptors/nem_namespace.py
sdk/python/generator/StructTypeFormatter.py
sdk/python/symbolchain/nc/__init__.py
sdk/python/symbolchain/nem/TransactionFactory.py
sdk/python/symbolchain/sc/__init__.py
sdk/python/symbolchain/symbol/TransactionFactory.py
sdk/python/tests/facade/test_BatchOperations.py
sdk/python/tests/vectors/catbuffer.py

problem: deserializer sets missing optional field to None but constructor sets it to default value
solution: initial optional fields with None in constructor too

[sdk/python]: initialize optional fields to None to match deserializer

---

client/catapult/tests/catapult/utils/CatapultExceptionTests.cpp

With boost 1.79, clang does not include the traits information in the exception function name as gcc.
Clang tests are failing
For Clang tests removed traits information from the exception function name.
Ran the Clang tests locally in docker.

[client/catapult] fix: failing clang tests

---

sdk/javascript/src/CryptoTypes.js
sdk/javascript/src/SharedKey.js
sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/src/nem/SharedKey.js
sdk/javascript/src/symbol/SharedKey.js
sdk/javascript/test/CryptoTypes_spec.js
sdk/javascript/test/nem/SharedKey_spec.js
sdk/javascript/test/symbol/SharedKey_spec.js
sdk/javascript/test/test/sharedKeyTests.js
sdk/javascript/vectors/all.js
sdk/python/tests/nem/test_SharedKey.py
sdk/python/tests/test/BasicSharedKeyTest.py
sdk/python/tests/vectors/all.py

This is change similar to #285 for JS.
All derive test vectors pass, additional tests for SharedKey derivation has been added, that mimic the ones from py version

[sdk/javascript]: js key derivation

---

sdk/javascript/test/Cipher_spec.js
sdk/python/tests/test_Cipher.py

problem: these tests will eventually be moved to message tests and become redundant
solution: remove them

[sdk]: drop combined shared key + encryption tests

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/extensions/mongo/plugins/lock_hash/tests/CMakeLists.txt
client/catapult/extensions/mongo/plugins/lock_secret/tests/CMakeLists.txt
client/catapult/tests/catapult/utils/CatapultExceptionTests.cpp

Catapult client building on Windows is failing
There are couple of errors
1. warning RC4005: 'WIN_TARGET_NAME' : redefinition
2. fatal error LNK1169: one or more multiply defined symbols found
1. remove the WIN_TARGET_NAME to fix the ``warning RC4005: 'WIN_TARGET_NAME' : redefinition``
2. update cmake files to use no deps for lock hash and lock secret tests to fix ``fatal error LNK1169: one or more multiply defined symbols found``
3. update the ConvertToExceptionFunctionName() to fix the exception tests with msvc
Tested both on Windows and locally with gcc/clang

[client\catatpult] fix: Windows tests failing

---

client/catapult/tests/catapult/utils/SpinReaderWriterLockTests.cpp

MultipleThreadsCanAcquireReaderLock test take long time to run in Windows containter. This cause the test to timeout and fail.
Increase the wait time for the MultipleThreadsCanAcquireReaderLock test case.
Yes, tested locally on Windows and Linux

[client/catapult] fix: increase timeout for multiple readerWriter locks

---

client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
client/catapult/extensions/mongo/CMakeLists.txt
client/catapult/extensions/zeromq/CMakeLists.txt
client/catapult/tests/bench/CMakeLists.txt
jenkins/catapult/runDockerBuildInnerBuild.py
jenkins/catapult/versions.properties
jenkins/docker/cpp.Dockerfile

Catapult client build fails on Ubuntu 22.04
Catapult client dependencies needs to be updated.
Catapult client dependencies were updated to the latest version which allow successful build on Ubuntu 22.04
Run the changes in Jenkins.

[catapult/client] fix: update dependencies version

---

client/catapult/extensions/zeromq/tests/ZeroMqEntityPublisherTests.cpp
client/catapult/extensions/zeromq/tests/test/ZeroMqTestUtils.h

On Windows ZeroMQ cannot connect to any address using 0.0.0.0 or ::.  It does not fail either.
Windows does not allow connecting to any address but ZeroMQ does not failed.
On Linux it seems to work by connecting to localhost.
See bug for more information - ``https://github.com/zeromq/cppzmq/issues/527``
Update the ZeroMQ tests to connect to a specific address
Yes, ran the tests on Windows and Linux.

[client/catapult] fix: ZeroMQ tests failing on Windows

---

client/catapult/extensions/mongo/src/MongoBulkWriter.h
client/catapult/tests/bench/crypto/hashers/HashersBench.cpp
jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/runDockerTestsInnerTest.py

Clang and metal builds are failing.
Metal builds requires rtti enable for rocksDB.
```
22:36:42  /usr/bin/ld: lib/libcatapult.cache_db.a(RocksPruningFilter.cpp.o):(.data.rel.ro._ZTIN7rocksdb16CompactionFilterE[_ZTIN7rocksdb16CompactionFilterE]+0x10): undefined reference to `typeinfo for rocksdb::Customizable'
22:36:42  collect2: error: ld returned 1 exit status
```
Clang fails due to implicit conversion.
```
22:36:25  /catapult-src/client/catapult/tests/bench/crypto/hashers/HashersBench.cpp:70:71: error: implicit conversion changes signedness: 'benchmark::IterationCount' (aka 'long') to 'unsigned long' [-Werror,-Wsign-conversion]
22:36:25                          state.SetBytesProcessed(static_cast<int64_t>(buffer.size() * state.iterations()));
22:36:25 …
```

[client\catapult] fix: rocksdb metal build and clang failure

---

sdk/python/symbolchain/impl/CipherHelpers.py
sdk/python/symbolchain/nem/MessageEncoder.py
sdk/python/symbolchain/symbol/MessageEncoder.py
sdk/python/tests/nem/test_MessageEncoder.py
sdk/python/tests/symbol/test_MessageEncoder.py
sdk/python/tests/test/BasicMessageEncoderTest.py

message encoder is a helper around encrypted (and encoded) messages
This is a helper to handle most common use cases of encryption in nem and symbol.
* the change uses already tested elements
* there are additional tests used that check encoding (structuring)

[sdk/python] message encoder

---

sdk/python/requirements.txt
sdk/python/symbolchain/nem/KeyPair.py

> Note: This is the default pull request template.
SLOOOW
changed SDKs Signer and Verifier to use pynacl
All existing tests pass, test vectors pass as well.
(Lint is passing ;) )
Branch might have wrong base and might need transplant onto sdk staging branch (?)

[sdk/python]: use pynacl for signature generation and verification

---

client/catapult/docs/BUILD-conan.md

The Conan build docs are incorrect for clang.
Update docs to specify the correct library for Clang.
Update VS compiler version
Locally with the updated steps

[client/catapult] fix: update catapult build docs for Conan

---

.github/buildConfiguration.yaml
sdk/python/tests/test_RuleBasedTransactionFactory.py

linters folder gets updated but other projects are not run
linters can be upgraded and cause failures in other projects
If the linters gets upgraded rerun all other projects
Also create workaround for the python sdk pylint failure and open this issue - ``https://github.com/PyCQA/pylint/issues/7381``

[jenkins] fix: add linters project as a dependency to all other projects

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

Discord message for fail Jenkins job need more information on the failure.
Add the stage name plus exception message to the discord message
Ran this in Jenkins.

[jenkins] fix: add stage name and exception message to Discord message for Jenkins failed jobs

---

client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
jenkins/catapult/compilers/ubuntu-clang/Dockerfile
jenkins/catapult/jenkins/catapult-client-build-base-image-all.groovy
jenkins/catapult/jenkins/catapult-client-build-base-image.groovy
jenkins/catapult/jenkins/catapult-client-build-compiler-image.groovy
jenkins/catapult/versions.properties

Upgrade to boost 1.80
catapult client will not use boost 1.80
change name from gcc-10 -> gcc-debian
Running tests in Jenkins now.  Will verify in the morning.

[client/catapult] fix: upgrade to boost 1.80

---

sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_SymbolFacade.py

problem: construction of Cosignatures is a bit awkward because it requires direct manipulation of catbuffer POD types
solution: add cosignTransaction helper function to SymbolFacade that hides the gory details

[sdk/javascript]: add cosignTransaction to SymbolFacade

---

sdk/python/symbolchain/CryptoTypes.py
sdk/python/symbolchain/nem/Network.py
sdk/python/symbolchain/symbol/Network.py
sdk/python/tests/test/BasicAddressTest.py
sdk/python/tests/test_CryptoTypes.py

problem: types that can be roundtripped should support repr
solution: add repr to these types

[sdk/python]: add repr to BasicArray derived types

---

jenkins/catapult/jenkins/catapult-client-release-build.groovy

private build of the catapult client tag has invalid git hash
This is a regression in https://github.com/symbol/symbol/commit/69b0753aaa7c8e8370794cc056760f4d4233bd0e
change the tag name to use the first 8 chars of the git hash
Ran the jenkins build

[jenkins] fix: catapult client private build tag name

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/plugins/txes/restriction_mosaic/tests/state/RestrictionValueMapTests.cpp
client/catapult/src/catapult/model/EntityRange.h
client/catapult/tests/catapult/model/TransactionTests.cpp
client/catapult/tests/catapult/model/VerifiableEntityTests.cpp
jenkins/catapult/runDockerTestsInnerLint.py

problem: lint failures don't fail build
solution: fail build on lint failure
problem: gcc 12 stringop-overread and array-bounds warnings are disabled
solution: enable those warnings and fix / disable individually

[catapult/client] build: fail on lint and individually disable gcc 12 warnings

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
client/catapult/plugins/txes/restriction_mosaic/tests/state/RestrictionValueMapTests.cpp
client/catapult/src/catapult/crypto/OpensslInit.cpp
client/catapult/src/catapult/crypto/OpensslInit.h
client/catapult/src/catapult/ionet/PacketSocket.cpp
client/catapult/src/catapult/model/EntityRange.h
client/catapult/src/catapult/process/ProcessMain.cpp
client/catapult/tests/catapult/model/TransactionTests.cpp
client/catapult/tests/catapult/model/VerifiableEntityTests.cpp
client/catapult/tests/test/nodeps/CMakeLists.txt
client/catapult/tests/test/nodeps/TestMain.cpp
client/catapult/tools/tools/ToolMain.cpp
jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/environment.py
jenkins/catapult/runDockerBuildInnerBuild.py
jenkins/catapult/runDockerBuildInnerPrepare.py
jenkins/catapult/runDockerTestsInnerLint.py
jenkins/catapult/runDockerTestsInnerTest.py
jenkins/catapult/templates/RunTestWindows.yaml
jenkins/catapult/versions.properties
linters/cpp/exclusions.py

problem: client is using openssl version that will be deprecated in 2023
solution: upgrade to latest 3.0.x version

[catapult/client]: upgrade openssl from 1.1.1x to 3.0.x

---

jenkins/catapult/jenkins/catapult-client-build-base-image-all.groovy
jenkins/catapult/jenkins/catapult-client-build-base-image.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project-daily.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project-weekly.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project.groovy
jenkins/catapult/jenkins/catapult-client-build-compiler-image-all.groovy
jenkins/catapult/jenkins/catapult-client-build-compiler-image.groovy
jenkins/catapult/jenkins/catapult-client-prepare-base-image.groovy
jenkins/shared-library/vars/helper.groovy

Catapult compiler and base image jobs are run manually.
Catapult compiler and base image jobs are not run on a regular schedule.
1. enable catapult client image jobs to run monthly
2. add a job that builds all the compiler images
3. add notification for when catapult jobs fails

[jenkins] fix: update catapult client jobs

---

client/catapult/src/catapult/ionet/PacketSocket.cpp
client/catapult/tools/ssl/CertificateDirectoryGenerator.h
client/catapult/tools/ssl/SslClient.cpp
client/catapult/tools/ssl/main.cpp

problem: clients are able to initiate connections without certificates
solution: require connections to provide certificates by passing SSL_VERIFY_FAIL_IF_NO_PEER_CERT

[catapult/client]: require connections to provide SSL certificate

---

client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
client/catapult/extensions/mongo/CMakeLists.txt
client/catapult/extensions/zeromq/CMakeLists.txt
client/catapult/tests/bench/CMakeLists.txt
client/catapult/tests/catapult/consumers/BatchSignatureConsumerTests.cpp
client/catapult/tests/catapult/utils/CatapultExceptionTests.cpp
jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/compilers/clang-latest.yaml
jenkins/catapult/compilers/clang-prior.yaml
jenkins/catapult/compilers/ubuntu-clang/Dockerfile
jenkins/catapult/dependency_flags.py
jenkins/catapult/installDepsLocal.py
jenkins/catapult/templates/UbuntuReleaseBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestSanitizerBaseImage.Dockerfile
jenkins/catapult/versions.properties

clang compiler and deps are outdated
bump the version of deps to the latest
1. clang latest to 15
2. cmake to 3.25
3. rocksdb to 7.7.3
4. benchmark to 1.7.1
5. mongo-c-driver to 1.22.2
6. mongo-cxx-driver to 3.7.0
7. cppzmq to 4.9.0

[client/catapult] fix: clang latest to 15 plus deps updates

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/conanfile.txt
client/catapult/extensions/mongo/CMakeLists.txt
jenkins/catapult/versions.properties

Catapult is not using the latest mongodb driver
Update to the latest mongodb drivers.
Running in Jenkins

[client/catapult] fix: update mongodb drivers

---

client/catapult/conanfile.txt
client/catapult/extensions/mongo/CMakeLists.txt
jenkins/catapult/versions.properties

Mongodb-c-driver fails to build on MacOs
getpagesize() is removed in the later OS.
Downgrade the mongodb-c-driver to allow MacOs builds to work
on dev box

[client/catapult] fix: revert mongodb version bump

---

jenkins/catapult/process.py
jenkins/catapult/runDockerTestsInnerTest.py

Occasionally catapult tests on Windows fails due to invalid bytes get included in the tests output.
```
15:52:24  catapult-client-build-catapult-project-test-1  | Failed to decode line: b'[----------] 1 test from FutureTests\xfb\xc0\r\n'
15:52:24  catapult-client-build-catapult-project-test-1  |  Exception: 'utf-8' codec can't decode byte 0xfb in position 36: invalid start byte
```
Instead of failing the tests run when decode of the output fails, it will log the failure and continue running the tests.
Ran in Jenkins

[jenkins] fix: handle testcase decode output failure 

---

sdk/javascript/wasm/Cargo.toml
sdk/javascript/wasm/src/lib.rs

problem: wee_alloc is no longer maintained
solution: always use default allocator

[sdk/javascript]: drop wee_alloc support

---

client/catapult/plugins/txes/mosaic/src/plugins/MosaicSupplyRevocationTransactionPlugin.cpp
client/catapult/plugins/txes/mosaic/tests/plugins/MosaicSupplyRevocationTransactionPluginTests.cpp

problem: ExtractAddresses should include MosaicSupplyRevocation::SourceAddress
solution: raise AccountAddressNotification
problem: revocation can be blocked by mosaic restriction(s)
solution: stop raising AddressInteractionNotification

[client/catapult]: MosaicSupplyRevocation is not correlated with SourceAddress

---

client/rest/resources/rest.json
client/rest/src/routes/networkRoutes.js
client/rest/test/routes/allRoutes_spec.js
client/rest/test/routes/networkRoutes_spec.js

problem: there is no way to determine inflation (block rewards) from rest
solution: add API returning contents of config-inflation
add API returning inflation given block height

[client/rest]: add inflation route(s)

---

jenkins/docker/python.Dockerfile

problem: ripemd160 is disabled in openssl 3 since its a legacy provider
solution: enable openssl 3 legacy provider
Tests that use ``ripemd160`` are failing.
In openssl 3 ``ripemd160`` is a legacy provider and is disabled by default.
Enabled the legacy provider in openssl 3 in the python ci image.
Ran tests on dev box

[jenkins] fix: openssl 3 legacy providers disabled by default

---

jenkins/shared-library/vars/publish.groovy

it was not possible to pass docker build args to docker publish task in the jenkins pipeline.
setting `config.dockerBuildArgs` parameter in the jenkins pipeline will be possible like the following:
```
defaultCiPipeline {
platform = ['ubuntu']
publisher = 'docker'
dockerImageName = 'nemofficial/nis-client'
dockerBuildArgs = "--build-arg GIT_BRANCH_NAME=${env.BRANCH_NAME}"
packageId = 'nem-infra'
}
```

[jenkins] feat: docker publish task optional build args param added

---

jenkins/infra/jenkins/build-ci-image-all.groovy
jenkins/infra/jenkins/build-ci-image.groovy
jenkins/shared-library/vars/defaultCiPipeline.groovy

Each Jenkins CI job has to build docker images
Building the docker image can take a long time or fail during CI.
Create docker images and host them in docker hub.  
The docker images be  pulled at CI time.  Later these will be cache for better performance.
Tested with Jenkins

 [jenkins] feat: add jenkins file to build ci images

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/compilers/windows-msvc/Dockerfile
jenkins/catapult/jenkins/catapult-client-prepare-base-image.groovy
jenkins/catapult/process.py
jenkins/catapult/runDockerBuild.py
jenkins/catapult/runDockerBuildInnerBuild.py
jenkins/catapult/runDockerTestsInnerTest.py
jenkins/catapult/templates/DebianTestBaseImage.Dockerfile
jenkins/catapult/templates/FedoraTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuReleaseBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestSanitizerBaseImage.Dockerfile
jenkins/catapult/templates/WindowsTestBaseImage.Dockerfile
jenkins/catapult/versions.properties

Catapult Windows builds takes a long time to build.
There was no caching on Windows for the build files.
ccache is now enabled as part of the Catapult build on Windows.  This reduces the build time by 40% to around 25 mins.
By default is it off due to an issue when ccache is installed by a package manager, Scoop or chocolatey, they will install a shim in the PATH instead of the actual binary for ccache.  CMake will copy the shim version.
It also requires using ``/Z7`` instead of ``Zi`` for generating the debug files
https://github.com/ccache/ccache/wiki/MS-Visual-Studio
Also change to use the latest Powershell 7 which uses UTF-8 by default.
By running in Jenkins.

[jenkins] fix: ccache for catapult Windows build

---

client/catapult/scripts/sdk/publishSdk.py
linters/cpp/HeaderParser.py
linters/cpp/Rules.py
linters/python/.pylintrc
sdk/python/generator/Generator.py
sdk/python/requirements.txt
sdk/python/symbolchain/nc/__init__.py
sdk/python/symbolchain/sc/__init__.py
sdk/python/tests/test_QrStorage.py
sdk/python/tests/vectors/catbuffer.py

With Pylint 2.16 catapult lint is failing with ``[W0719(broad-exception-raised), require_non_existence] Raising too general exception: Exception``.
This is due to pylint adds a new checker for broad-exception-raised - ``https://github.com/PyCQA/pylint/issues/7494``
Switch from Exception to RuntimeError 
Run the linting on dev box.

[client/catapult] fix: catapult pylint failure

---

jenkins/catapult/baseImageDockerfileGenerator.py

Conan 2 was released and got installed in catapult image.
Openssl recipe is not compatible with Conan 2.
open issue on Conan - ``https://github.com/conan-io/conan/issues/13322``
Only install Conan versions less than 2.
Tested locally on dev box.

[jenkins] fix: install conan 1.x

---

catbuffer/schemas/nem/multisig/multisig.cats
sdk/javascript/src/nem/models.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/python/symbolchain/nc/__init__.py
sdk/python/tests/facade/test_NemFacade.py

There's no model for NEM 'non-verifiable' multisig.
Added proper model + cosignatures are not included inside non-verifiable, as they screw up hash/signature calculations.
Tested in NEM network 😎

Missing models for NEM non-verifiable aggregate (multisig) transaction

---

sdk/javascript/src/symbol/Network.js
sdk/python/symbolchain/symbol/Network.py

The epoch adjustment value is invalid (it wasn't updated during the post-reset configuration update).
Fix testnet epoch adjustment value to reflect the current sai network.

Fix: SDK - Testnet epoch adjustment value

---

client/rest/package-lock.json
client/rest/package.json
client/rest/resources/rest.json
client/rest/src/db/CatapultDb.js
client/rest/src/db/connector.js
client/rest/src/index.js
client/rest/src/routes/nodeRoutes.js
client/rest/test/routes/nodeRoutes_spec.js

Rest endpoint ``/node/health`` shows mongodb database down
starting with mongo driver 4.x, mongodb removed the isconnected() method
see #203 
add logic to ping admin db to verify if db is available.
also reduce the connection timeout to 10s but configurable from config.
if mongodb is down it will take 10s for the ``/node/health`` endpoint to return.
Tested on dev box.

[client/rest] fix: rest shows mongodb down 

---

client/rest/package-lock.json
client/rest/src/db/CatapultDb.js
client/rest/test/server/bootstrapper_spec.js

websocket connections are not been closed.
some of the websocket tests occasionally fails. 
```
1) server (bootstrapper)
websockets
handles unsubscription of client from unknown channel:
Error: Address already in use
```
close the client ws connections to the server
I am not able to repo this issue but from looking at the tests this is what I think the issue might be.

[client/rest] fix: websocket tests fails with socket in use

---

client/rest/Dockerfile

Rest client docker image is increased in size compared to the previous version
The base image was switched from Ubuntu 20.04 to node:lts
Switch back to use Ubuntu as the base image plus use docker multi-stage build.
The sizes of each version is listed below where v2.4.3 is build using the Dockerfile from this PR.
```
docker images
REPOSITORY                     TAG              IMAGE ID       CREATED          SIZE
symbolplatform/symbol-rest     2.4.3            2230ce4a1a04   15 seconds ago   406MB
symbolplatform/symbol-rest     2.4.2            bc52220035c3   4 months ago     1.17GB
symbolplatform/symbol-rest     2.4.0            cedc875cd97a   16 months ago    826MB
```
Tested the image locally on dev box and do not see any issues calling rest endpoint.

[client/rest] fix: reduce docker image size

---

client/catapult/scripts/ci/setup_test.sh
client/rest/scripts/ci/setup_test.sh
jenkins/docker/cpp.Dockerfile
jenkins/docker/javascript.Dockerfile
sdk/javascript/src/impl/ed25519.js
sdk/javascript/webpack.config.js

build of the ci javascript and cpp images are failing due to the removal of libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb from ubuntu
https://jenkins.symboldev.com/job/infra/job/build-ci-image/15/console
Upgrade to mongodb 6.0.4 which does not need openssl by default.
build the images locally to test

[jenkins] fix: remove openssl 1.1.1f dependency

---

client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
client/catapult/docs/BUILD-manual.md
client/catapult/src/catapult/crypto/OpensslContexts.cpp
client/catapult/src/catapult/crypto/OpensslContexts.h
jenkins/catapult/versions.properties

catapult client is using an older version of openssl
upgrade openssl to version v3.1.0
ran the catapult tests on my dev box.

[client/catapult] fix: upgrade to openssl 3.1.0 

---

jenkins/catapult/templates/RunTest.yaml
jenkins/catapult/templates/RunTestWindows.yaml

catapult is been tested against mongo 4.x
update catapult tests to use the latest mongodb 6
Ran tests on my dev box

[jenkins] fix: update catapult tests to use mongodb 6

---

client/rest/CHANGELOG.md
client/rest/package-lock.json
client/rest/package.json
client/rest/test/routes/nodeRoutes_spec.js

Change log is outdated.
Prepare change log for 2.4.3 release

[client/rest] fix: prepare release 2.4.3

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/extensions/addressextraction/src/AddressExtractor.cpp
client/catapult/extensions/addressextraction/tests/AddressExtractorTests.cpp

problem: if a resolution entry is added for a transaction, it should stay in scope for the rest of the block
AddResolvedAddresses is incorrectly scoping a resolution entry to the transaction that triggered it
solution: extend the scope of a resolution entry to last until the end of the block

[client/catapult]: AddResolvedAddresses is not properly applying resolutions from previous transactions

---

client/rest/src/db/CatapultDb.js
client/rest/test/db/CatapultDb_spec.js

problem: raw mongodb storage statistics are not reported through REST API
solution: extend node/storage to include database-wide statistics

[client/rest]: report mongodb database size in /node/storage

---

client/catapult/tests/int/node/stress/HappyBlockchainIntegrityTests.cpp

HappyBlockchainIntegrityTests hangs occasionally
HappyBlockchainIntegrityTests hangs randomly during test run causing incomplete runs in the CI
HappyBlockchainIntegrityTests is disabled by default.
Create issue ``#616`` for track this.
Ran locally to verify that the tests does not run

[client\catapult] fix: disable HappyBlockchainIntegrityTests

---

linters/javascript/default.eslintrc
sdk/javascript/src/impl/CipherHelpers.js
sdk/javascript/src/impl/ed25519.js
sdk/javascript/src/nem/MessageEncoder.js
sdk/javascript/src/nem/SharedKey.js
sdk/javascript/src/symbol/TransactionFactory.js
sdk/javascript/test/nem/MessageEncoder_spec.js
sdk/javascript/test/symbol/idGenerator_spec.js

Unsorted named imports are ignored by the linter.
Named imports are not consistent and it is hard to find a member in a large list.
- Added `sort-imports` rule to `javascript/default.eslintrc`.
- Added `ignoreDeclarationSort` property to only affect member sorting and make it compatible with the `import/order` rule.
❌
```js
import { b, a, c } from 'foo.js';
```
✔️
```js
import { a, b, c } from 'foo.js';
```

[linters] feat: add the sort-imports eslint rule

---

client/catapult/tests/catapult/ionet/PacketSocketTests.cpp
client/catapult/tests/test/net/ClientSocket.cpp
client/catapult/tests/test/net/ClientSocket.h
client/catapult/tests/test/net/SocketTestUtils.cpp
client/catapult/tests/test/net/SocketTestUtils.h

catapult ionet tests occasionally fails on Windows
catapult client ionet tests are failing on Windows due to race condition due to the server socket getting closed before the read is complete by the client.
add synchronization between the server and client threads so the server thread waits for read to be completed before the server thread exit.
tested local on Windows and Linux nodes.
Havent been able to reproduce the issue on Windows.

[client/catapult] fix: catapult client ionet failing on Windows

---

jenkins/shared-library/vars/publish.groovy

docker build fails for the REST Image
npm install is hangs/unable to reach some sites
add ``--network host`` flag to the docker build
tested in jenkins
https://jenkins.symboldev.com/job/Symbol/job/generated/job/symbol/job/rest/job/fix%252Fdocker_build_hang/4/console

[jenkins] fix: docker build hangs due to network

---

sdk/javascript/package.json

npm package is missing the wasm pkg
npm publish does include the correct set of files
add a file list to package.json to include wasm pkg
tested by running ``npm publish --dry-run``

[sdk/javascript] fix: specify which files to publish

---

jenkins/catapult/jenkins/catapult-client-build-catapult-project.groovy

Catapult code coverage upload by codecov is empty.
Even though Codecov was able to discover the code coverage file in the git repo, codecov tool needs to be run from within the git repo folder.
Change the current working folder to the git repo
Ran a job in Jenkins and it seems to upload successfully.

[client/catapult] fix: catapult client code coverage show as empty

---

jenkins/catapult/runDockerTestsInnerTest.py

Catapult client address sanitizer tests are failing due to false positive detection of alloc/dealloc mismatch
There is a known issue ``https://github.com/llvm/llvm-project/issues/52771`` where AddressSanitizer feature reports that  alloc/dealloc test fails when an exception is thrown.
disable the address sanitizer alloc/dealloc mismatch feature until the bug is fix.
Ran tests locally in docker

[jenkins] fix: disable ausan alloc/dealloc mismatch due false positive

---

client/catapult/CMakeGlobalSettings.cmake
client/catapult/sanitizer_ignorelist.txt

Catapult ausan tests are failing due to implicit conversion detection in boost multiprecision code.
In the boost import_export.hpp header, its casting an unsigned to signed value which reports this error
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /mybuild/include/boost/multiprecision/cpp_int/import_export.hpp:112:54 in 
/mybuild/include/boost/multiprecision/cpp_int/import_export.hpp:112:42: runtime error: implicit conversion from type 'unsigned long' of value 18446744073709551608 (64-bit, unsigned) to type 'difference_type' (aka 'long') changed the value to -8 (64-bit, signed)
```
disable UndefinedBehaviorSanitizer detection for the boost multiprecision import_export.hpp file
also opened a bug on boost: https://github.com/boostorg/multiprecision/issues/556
Ran the test …

fix: disable UndefinedBehaviorSanitizer for implicit conversion in boost multiprecision code

---

jenkins/catapult/baseImageDockerfileGenerator.py

Catapult MongoDB tests are failing in thread sanitizer(tsan) run 
Thread sanitizer can report false positive when third party modules are not instrumented(i.e. compiled with -fsanitize=thread option).
Build the MongoDB drivers with thread sanitizer enabled( -fsanitize=thread) when building the catapult base image for tsan.
rebuild the catapult tsan image and reran the tsan tests.

[jenkins] fix: catapult tsan mongodb tests

---

jenkins/shared-library/vars/createMonorepoMultibranchJobs.groovy

Active multibranch jobs are getting remove when the job cleanup code runs
Multibranch job cleanup logic remove active jobs that are not in the current branch job configuration.
This is not correct since new projects that are not in dev branch will need their ci jobs.
When projects are removed or moved, the old multibranch job will not have any active jobs.
Add a check to make sure multibranch job has at least one active job for a branch before deleting it.
The downside of this is if someone manually creates a multibranch job then it will not be delete which should be OK.
Tested in Jenkins

[jenkins] fix: check if multibranch job is active

---

jenkins/docker/postgres.Dockerfile
jenkins/infra/jenkins/build-ci-image.groovy

postgres docker image fails to build since its not able to find Java 11 package to install.
This seems postgres:15 update the base image to debian:bookworm-slim which only have Java 17.
switch the postgres ci image to use the postgres:bulleye as the base image.
Also add missing checkout step in the CI job.
Test by building the docker image local

[jenkins] fix: postgres docker image fails to build

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

Jenkins does not set any of the parameters to default values during branch discovery job.
Catapult project depends on the ARCHITECTURE value to be set but it is null during branch discovery jobs.
Set the default value for ARCHITECTURE so its available for the entire pipeline
Currently testing in Jenkins

[jenkins] fix: ARCHITECTURE value is missing during branch discovery

---

.github/dependabot.yaml

Javascript wasm sdk dependencies are not getting updated.
Dependabot is not configured for the Javascript SDK wasm folder.
Enable dependabot update for Javascript SDK wasm folder.

[monorepo] fix: enable dependabot update for Javascript Wasm sdk

---

jenkins/docker/javascript.Dockerfile

Javascript SDK fails to build wasm module on Linux arm64 due to missing dependencies.
openssl-sys requires libssl-dev and pkg-config to be installed but not sure it currently works on amd64  - https://docs.rs/crate/openssl-sys/0.9.19
there is no aarch64 build of binaryen so build with fails due to no wasm_opt - https://github.com/WebAssembly/binaryen/issues/5337
Install libssl-dev and pkg-config package in the CI image.
Install binaryen on arm64 Linux to be able to use the wasm_opt feature.  This is not needed for amd64 since wasm_pack will use the prebuilt binary
Tested on arm64 linux

[jenkins] fix: Javascript sdk fails to build on arm64 Linux

---

jenkins/docker/python.Dockerfile
jenkins/infra/jenkins/build-ci-image-all.groovy
jenkins/infra/jenkins/build-ci-image.groovy

Test are only run in Ubuntu 22.04
shoestring is run on multiple version of Ubuntu which leads to failures for end users on Ubuntu 20.04 and Ubuntu 23.04.
create test images for Ubuntu 20.04 and 23.04 which will be run on a weekly schedule.
run docker build locally to test.

[jenkins]: add support to build different version of python images

---

.gitignore
sdk/javascript/CHANGELOG.md
sdk/javascript/package-lock.json
sdk/javascript/package.json
sdk/javascript/scripts/ci/build.sh
sdk/javascript/src/utils/base32.js
sdk/javascript/tsconfig-generate.json
sdk/javascript/tsconfig.json
sdk/python/CHANGELOG.md
sdk/python/pyproject.toml

* export base32 as out of line functions to preserve documentation
* generate TS files in ts/ folder
* include ts/ folder in package
* bump version

[sdk/javascript]: TS publishing fixes

---

jenkins/catapult/templates/RunTest.yaml

docker-compose ``depends_on`` by default does not wait for the MongoDB service to be ready, only for the container to be running.
Catapult tests will start before the MongoDB service is ready.  This will cause some Catapult MongoDB tests to fail.
Add a health check for the MongoDB container which make the service ready once it is up and running
Catapult tests will now wait for the MongoDB service to be healthy instead of the container to run.
Ran the docker-compose locally to verify.

[jenkins]: fix race condition with MongoDB starting and Catapult tests running

---

jenkins/docker/python.Dockerfile
jenkins/infra/jenkins/build-ci-image.groovy

Ubuntu 20.04 ships with Python 3.8
Python 3.9 is now the minimum requirement for all Python projects but Ubuntu 20.04 ships with Python 3.8
Install Python 3.9 on Ubuntu 20.04 and set it as the default version.
Build the images locally on my dev box.

[jenkins]: install python 3.9 on Ubuntu 20.04

---

jenkins/docker/ubuntu/javascript.Dockerfile

JavaScript projects are using Node 16.
Node 16 has reached the End Of Life.
Upgrade the JavaScript image to use Node 18.
It was tested locally.

[jenkins] fix: Upgrade to Node 18 for CI builds

---

sdk/javascript/src/nem/MessageEncoder.js
sdk/python/symbolchain/RuleBasedTransactionFactory.py
sdk/python/tests/test_RuleBasedTransactionFactory.py

[sdk/python]: fixes for python 3.11
problem: 3.11+ removes named zero flags from Flag class
solution: manually add 'none' => 0 mapping in add_flags_parser
[sdk/javascript]: fixes for Node 18
problem: exceptions filtered by MessageEncoder (NEM) are too specific
solution: use more generic filters that work with both Node 16 and 18

[sdk] fixes for node 18 AND  fixes for python 3.11

---

client/rest/Dockerfile

Rest image ships with Node 16
Rest is using an unsupported Node version
Upgrade to Node 18 which is the latest LTS.
Tested locally on my dev box

[client/rest] fix: update rest image to node 18

---

.github/buildConfiguration.yaml
.github/jenkinsfile/weeklyBuild.groovy
sdk/javascript/Jenkinsfile
sdk/javascript/scripts/ci/lint_python.sh
sdk/python/Jenkinsfile
sdk/python/scripts/ci/lint.sh

JavaScript and Python SDKs only test in one environment
JavaScript and Python SDKs cannot run tests in other Python environments
Enable weekly builds for JavaScript and Python SDKs.
JavaScript SDKs will run in a Windows environment
Python SDKs will run in Windows and different versions of Python on Ubuntu.
Tested locally and in Jenkins.
The build will currently fail with Python 3.11.

[monorepo] task: Enable weekly builds for JavaScript and Python sdks

---

jenkins/catapult/jenkins/catapult-client-release-build.groovy
jenkins/shared-library/vars/configureArtifactRepository.groovy
jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/dockerHelper.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/publish.groovy
jenkins/shared-library/vars/runScript.groovy

All packages are updated from the public artifact repository.
Projects need to push test artifacts to a public repository.
Currently have no support for private artifact repos.
The following have been added to Jenkins.
1. Add support to publish to private NPM, PyPi, and Docker repositories.
2. Add support to install packages from a private repository during CI
3. Private GitHub repository always publishes to private artifact repo.
The Nexus OSS version has certain limitations.  One been is that artifacts cannot be pushed to a group repository.
Jenkins will configure the pull from the group repo and push it to the hosted repo.

[jenkins] feat: setup private repository

---

jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/nightlyBuildPipeline.groovy
jenkins/shared-library/vars/weeklyBuildPipeline.groovy

All tests are run during CI.
Some test suite(such as example & vector) takes longer to run.
Only run the unit tests during CI.
All the tests are executed during the nightly builds.

[jenkins] fix: only run unit test during CI

---

jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/helper.groovy

Jenkins includes the branch name as part of the workspace folder name.
C++ compilation which uses marco like ``__FILE__``, will cause ccache to have a lot of cache misses due to the differences in path.  This leads to longer compile times for Catapult.
https://ccache.dev/manual/latest.html#_compiling_in_different_directories
Add a custom workspace for CI builds.  This will allow faster builds for Catapult client.
Tested locally and it seems to be faster.

[jenkins] fix: add custom workspace for CI builds

---

jenkins/shared-library/vars/publish.groovy

Jenkins only has permission to its own AWS account.
Jenkins cannot publish to different AWS accounts.
Add a generic AWS publisher which will set up credentials for a specific AWS account.
the published script will run to all specific operations on the AWS account.
locally on my dev box.

[jenkins] feat: add generic AWS publisher to Jenkins

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

Since not all tests are run during CI then code coverage will fail to meet the minimum requirement.
If code coverage runs it will cause Codecov to report failure since there is a drop in coverage.
During CI, disable code coverage if there are other tests defined other than unit tests for the project.
Nightly builds will run all tests and fail if the code coverage limit is not met.
Tested in Jenkins

[jenkins] fix: Code coverage fails the CI job when expected.

---

jenkins/catapult/jenkins/catapult-client-build-catapult-project-daily.groovy
jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/nightlyBuildPipeline.groovy

CI builds are run on Intel architecture
Intel architecture is usually slower than ARM.
Switch to using ARM architecture as the default for CI.
Catapult daily builds will run on alternate days for intel and ARM.
Will test in Jenkins.

[jenkins] fix: switch to using ARM for CI builds

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

Verify commit enforces max body line length for every commit
For Dependabot and grouping of the Dependabot PRs, the max body length can exceed the max length value.
This causes the CI job to fail in the verify commit message stage.
Disable max body line length check for For Dependabot and grouping of the Dependabot PRs.
Tested locally on dev box.

[jenkins] fix: disable body max line length rule for dependencies commits

---

jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/templates/FedoraTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestSanitizerBaseImage.Dockerfile
jenkins/catapult/templates/WindowsTestBaseImage.Dockerfile

pylint 3.x has breaking change by the removal of pylint.interfaces.
This breaks the pylint quotes plugin which is used in our linting
``https://github.com/pylint-dev/pylint/issues/9094#issuecomment-1743859788``
downgrade to pylint 2.x until all plugins supports pylint 3.x
Tested in Jenkins

[jenkins] fix: downgrade pylint to 2.x

---

jenkins/shared-library/vars/runTests.groovy
sdk/python/examples/docs/__main__.py
sdk/python/examples/docs/__main__.py.tmpl

Python SDK requests tokens from the faucet.
The faucet requires a Twitter user to get tokens.
Update the Python SDK tests to use a seed account to get tokens
Ran scripts on my dev box to test.

[sdk/python] fix: remove the requirement of faucet for tests

---

jenkins/catapult/jenkins/catapult-client-build-base-image-all.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project-daily.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project-weekly.groovy
jenkins/catapult/jenkins/catapult-client-build-compiler-image-all.groovy
jenkins/infra/jenkins/build-ci-image-all.groovy
jenkins/infra/jenkins/build-ci-image.groovy

Alternating builds between arm64 and amd64 are not working correctly due to the ``ARCHITECTURE = helper.determineArchitecture()`` which sets a local variable instead of the env value.
This would cause one of the architecture images not to build and become stale.
Set the ``env.ARCHITECTURE`` when calling the helper.determineArchitecture().
Will test in Jenkins

[jenkins] fix: CI and Catapult images can be stale

---

jenkins/docker/ubuntu/linter.Dockerfile

The latest CI image now has npm-groovy-lint 12.  This requires Java 17.  I created new images with Java 17 which works on AMD but fails on ARM with ``Unsupported architecture``.
Already couple of issues on this - https://github.com/nvuillam/npm-groovy-lint/issues/296#issuecomment-1802168710
Downgrade ``npm-groovy-lint`` to 11.x until the issues are resolved.
Tested locally on my Mac.

[jenkins] fix: downgrade npm-groovy-lint to 11.x

---

jenkins/shared-library/vars/codeCoverage.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/publish.groovy

Jenkins job for private repo will fail on Codecov uploads which we cannot fix.
Codecov has a 250 upload limit for private repo after which uploads will fail.
Codecov also throttles uploads when they are too frequent.
For private repo, do not pass the ``--nonZero`` flag to Codecov which forces a returned code on failure.

[jenkins] fix: ignore codecov upload failures for private repo

---

jenkins/docker/ubuntu/linter.Dockerfile

Linter Dockerfile is missing the NodeJs version required to build.
Set the NodeJs version to 18

[jenkins] fix: linter dockerfile missing node version

---

jenkins/docker/windows/javascript.Dockerfile
jenkins/docker/windows/python.Dockerfile
jenkins/shared-library/vars/runScript.groovy
sdk/javascript/examples/transaction_sign.js
sdk/javascript/package.json
sdk/javascript/scripts/run_catbuffer_generator.sh
sdk/python/scripts/run_catbuffer_generator.sh
sdk/python/scripts/run_examples_docs_generator.sh
sdk/python/scripts/run_testvectors_generator.sh

1. Windows by default installs Python 3.12 which is not supported by aiohttp
``https://github.com/aio-libs/aiohttp/issues/7646``
2. build scripts fail to diff current JSON files with the generated file on Windows due to extra ``cr``.
3. Javascript SDK is failing to build on Windows due to
a. build using the linker from the git package instead of VS
b. run of the vector scripts failed since Windows shell does not know BLOCKCHAIN env.  Windows shell requires %BLOCKCHAIN% vs ${BLOCKCHAIN}
c. import file does match URL format(https://nodejs.org/api/esm.html#file-urls)
1. Windows install Python 3.11 which is supported by aiohttp
2. Ignore ``cr`` on the diff of JSON files.
3. Javascript SDK updates
a. Put the VS tool first in the PATH in the user profile.
b. run the vector scripts with bash so …

[sdk] fix: Update the Javascript and Python SDKs to run on Windows.

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

The last git commit author is returned by executing ``git log`` in the cmd shell.
Jenkins will return the command line plus the output of the command when ``bat`` is called.
This causes the check for the author names to fail for dependabot and thus max line length is not disabled for gitlint.
Use ```sh`` to get the git author name which returns the correct value.

[jenkins] fix: git verify commit message fails on Windows

---

jenkins/shared-library/vars/defaultCiPipeline.groovy

On Windows links to the submodule are not created correctly.
The links are created before the submodule file/directory is present.
Windows does not handle this correctly.
Call the init scripts which will re-create links.
Tested with Jenkins.

[jenkins] fix: always call init script

---

client/catapult/docs/BUILD-conan.md

catapult docs has the old endpoint used when building with Conan
update the catapult docs with the latest endpoint
issue: https://github.com/symbol/symbol/issues/790

[client/catapult] fix: update catapult conan artifact endpoint

---

.github/jenkinsfile/controller.groovy
jenkins/shared-library/vars/changedSetHelper.groovy
jenkins/shared-library/vars/createMultibranchJob.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/jobHelper.groovy
jenkins/shared-library/vars/monorepoControllerPipeline.groovy
jenkins/shared-library/vars/monorepoSeedPipeline.groovy
jenkins/shared-library/vars/nightlyBuildPipeline.groovy
jenkins/shared-library/vars/weeklyBuildPipeline.groovy

All the CI jobs are triggered by GitHub calling into Jenkins.
For new branch/PR, Jenkins will do branch indexing where it does not have knowledge of the change list.
This will cause all the CI jobs to run.
A controller job has been added to manage which CI jobs to run.  The controller job will get the files in the commit and trigger the required CI jobs.
The controller job will get changed list in the following order
1. Check the ``currentBuild.changeSets`` Jenkins object for the files needs to build.
2. If pull request, get the file list from the PR
3. If all else fails, get the list of files from the last commit.
The file list is used to build a list of CI job that needs to be run.  The controller will trigger the jobs and wait for complete.
The controller job will now also create and …

[jenkins] fix: add a controller job to manage CI builds

---

jenkins/shared-library/vars/createMultibranchJob.groovy
jenkins/shared-library/vars/jobHelper.groovy

Jenkins jobs are not configured to run for PRs from the forked repo
Not able to manually run Jenkins job for outside contributor 
Allow an admin to run Jenkins job for outside contributors manually 
Added ``readTrusted`` for the build configuration file to prevent an outside contributor from modifying it.
Tested in Jenkins

[jenkins] fix: add support for untrusted repo

---

.github/buildConfiguration.yaml
.github/jenkinsfile/catapultDependency.groovy
jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/catapultDependencyUpdater.py
jenkins/catapult/installDepsLocal.py
jenkins/catapult/requirements.txt
jenkins/catapult/versions.properties
jenkins/shared-library/vars/codeCoverage.groovy
jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/gitPullRequestPipeline.groovy
jenkins/shared-library/vars/githubHelper.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/publish.groovy

Catapult dependency are updated manually.
Manually checking for dependency is not scalable and requires someone to remember
Add a Jenkins job which will run once a month to check for new updates.
The version check is done against Conan since their is a dependency for Conan builds.
Tested the updater script locally

[jenkins] feat: catapult dependency updater

---

jenkins/docker/ubuntu/cpp.Dockerfile

The cpp image does not create a virtual environment for Python.
Without a virtual Python environment, there will be package conflicts on installation.
Create a virtual python environment for the cpp image.
It is tested locally on dev box.

[jenkins] fix: add virtual python environment

---

client/rest/src/db/CatapultDb.js
client/rest/src/routes/blockRoutes.js
client/rest/test/db/CatapultDb_spec.js
client/rest/test/db/utils/dbTestUtils.js
client/rest/test/routes/blockRoutes_spec.js

Could not filter blocks by timestamp
Blocks can be filtered by timestamp

block_filterd_timestamp

---

client/rest/test/server/bootstrapper_spec.js

problem: tests are failing because requests are implicitly being sent with keep-alive
solution: explicitly send requests with `Connection: close` header

[client/rest]: fix failing bootstrapper tests

---

catbuffer/parser/catparser/CatsLarkParser.py
jenkins/catapult/runDockerTestsInnerLint.py
jenkins/catapult/templates/FedoraTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestSanitizerBaseImage.Dockerfile
jenkins/catapult/templates/WindowsTestBaseImage.Dockerfile
jenkins/docker/ubuntu/javascript.Dockerfile
jenkins/docker/ubuntu/python.Dockerfile
jenkins/docker/windows/javascript.Dockerfile
jenkins/docker/windows/python.Dockerfile
jenkins/infra/jenkins/build-ci-image.groovy
jenkins/shared-library/resources/buildEnvironment/baseImages.yaml
linters/python/.pylintrc
linters/python/lint.sh
linters/python/lint_requirements.txt
sdk/javascript/scripts/ci/lint_python.sh
sdk/python/scripts/ci/lint.sh
sdk/python/testvectors/__main__.py

Tests are currently not run with Python 3.12
Python 3.12 is now the default version on some Linux distributions.
Use Python 3.12 for testing in the latest image.
Move to Pylint 3, which supports Python 3.12
Remove Pylint-Quotes since does not support Pylint 3
Will run tests in Jenkins.

[monorepo] fix: update latest test image to use python 3.12

---

jenkins/docker/ubuntu/python.Dockerfile
jenkins/docker/windows/python.Dockerfile

problem: CFFI requires setuptools to be installed with Python 3.12
solution: install setuptools by default in the Python CI image

[jenkins] fix: CFFI failing to install on Python 3.12

---

jenkins/catapult/jenkins/catapult-client-build-base-image-all.groovy

problem: san test image are not built every month.
this leads to errors when the OS is upgraded.
solution: add the san test image in the build all base image job

[jenkins] fix: add san test image to monthly build

---

sdk/javascript/src/RuleBasedTransactionFactory.js
sdk/javascript/src/nem/Network.js
sdk/javascript/src/symbol/Network.js
sdk/javascript/test/RuleBasedTransactionFactory_spec.js
sdk/javascript/test/nem/Network_spec.js
sdk/javascript/test/symbol/Network_spec.js
sdk/javascript/vectors/BlockFactory.js

problem: NAME is not added to generated model classes, so they can not be used in descriptors
solution: add fallback logic when NAME is not provided

[sdk/javascript]: fix failing test vectors after constructor.name change

---

jenkins/catapult/baseImageDockerfileGenerator.py

problem: The catapult test layer limits the Pylint version
solution: remove Pylint version install limit

[jenkins] fix: remove Pylint version limit for catapult base image

---

sdk/javascript/src/Cipher.js
sdk/javascript/src/impl/ed25519_wasm.js

[sdk/javascript]: disable instance of eslint warning 'import/no-extraneous-dependencies'
problem: warning is raised when importing optional 'symbol-crypto-wasm-node'
solution: disable warning
[sdk/javascript]: update Cipher.js to support ReactNative environment
problem: ReactNative Buffer polyfill only allows Buffers to be passed to Buffer.concat
solution: all Uint8Arrays must be wrapped in Buffer when calling crypto cipher APIs

[sdk/javascript]: additional changes for ReactNative support

---

client/catapult/CMakeLists.txt
client/catapult/conanfile.txt
jenkins/catapult/versions.properties

problem: catapult is not using the latest OpenSSL version
solution: update OpenSSL to version 3.2.1

[client/catapult] fix: update OpenSSL to 3.2.1

---

client/rest/test/db/CatapultDb_spec.js

problem: db is not closed when a db test fails
solution: always close db

[client/rest]: prevent hangs in failing db tests

---

sdk/javascript/package.json

[sdk/javascript]: mm-snap requires default export to be last

---

linters/python/lint_requirements.txt
sdk/javascript/generator/StructTypeFormatter.py
sdk/python/generator/StructTypeFormatter.py

problem: Pylint 3.1.0 fails linting with ``use-yield-from`` for fields iterator
solution: update the generator function to use ``yield from`` instead of ``yield`` for the iterator

[sdk] fix: linting failure with use-yield-from

---

sdk/javascript/src/impl/ed25519.js

problem: sdk can't run in browser where global is not defined
solution: replace global with globalThis (resolves to window)

[sdk/javascript]: use globalThis instead of global

---

jenkins/docker/ubuntu/javascript.Dockerfile

problem: Javascript image does not have rust installed
solution: run rustup during Javascript image creation to install the latest rust

[jenkins] fix: install rust in Javascript image

---

sdk/python/generator/Generator.py
sdk/python/generator/TypeFormatter.py
sdk/python/symbolchain/nc/__init__.py
sdk/python/symbolchain/sc/__init__.py

problem: Pylint 3.1 fails in Python 3.12 due to ByteString is deprecated
https://docs.python.org/3.12/library/typing.html#typing.ByteString
solution: Replace the ByteString with ``bytes | bytearray | memoryview``

[sdk/python] fix: ByteString is deprecated in Python 3.9

---

sdk/javascript/README.md
sdk/javascript/examples/bip32_keypair.js
sdk/javascript/examples/descriptors/nem_mosaic.js
sdk/javascript/examples/descriptors/symbol_lock.js
sdk/javascript/examples/descriptors/symbol_mosaic.js
sdk/javascript/examples/descriptors/symbol_namespace.js
sdk/javascript/examples/examples_utils.js
sdk/javascript/examples/readme/nem.js
sdk/javascript/examples/readme/symbol.js
sdk/javascript/examples/transaction_aggregate.js
sdk/javascript/examples/transaction_multisig.js
sdk/javascript/examples/transaction_sign.js
sdk/javascript/package.json
sdk/javascript/src/index.js
sdk/javascript/src/index.web.js
sdk/javascript/src/nem/index.js
sdk/javascript/src/symbol/index.js
sdk/javascript/webpack.config.js

problem: sdk does not support named imports
solution: restructure and split up module entry points
allow usage like:
```js
import { PrivateKey } from 'symbol-sdk';
import { SymbolFacade } from 'symbol-sdk/symbol';
```

[sdk/javascript]: split single entry point into default, nem and symbol

---

sdk/javascript/README.md
sdk/javascript/examples/bip32_keypair.js
sdk/javascript/examples/readme/nem.js
sdk/javascript/examples/readme/symbol.js
sdk/javascript/examples/transaction_aggregate.js
sdk/javascript/examples/transaction_multisig.js
sdk/javascript/examples/transaction_sign.js
sdk/javascript/scripts/ci/build.sh
sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/src/nem/TransactionFactory.js
sdk/javascript/src/symbol/TransactionFactory.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/javascript/test/nem/TransactionFactory_spec.js
sdk/javascript/test/symbol/TransactionFactory_spec.js
sdk/javascript/tsconfig/build-bindings.json
sdk/javascript/tsconfig/check-bindings.json
sdk/javascript/tsconfig/check-examples.json

problem: examples are not TS compliant
solution:
- add static getter that can be used instead of constructor in TS
- update examples

[sdk/javascript]: run ts compiler over examples

---

sdk/javascript/src/NetworkTimestamp.js
sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/NetworkTimestamp_spec.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/symbolchain/NetworkTimestamp.py
sdk/python/symbolchain/facade/NemFacade.py
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py
sdk/python/tests/test_NetworkTimestamp.py

problem: calling network.fromDatetime is a bit verbose
solution: add now

[sdk]: add now to facade to simplify timestamp creation 

---

client/catapult/Jenkinsfile

problem: the latest docker version requires a subnetwork when a static IP address is used.
solution: specify the network that has the static IP address

[jenkins] fix: the latest docker requires subnet for static ip

---

jenkins/docker/windows/python.Dockerfile

problem: escape character for Windows Dockerfile should be backtick and not backslash
solution: update the escape character to the backtick

[jenkins] fix: escape character from backslach to backtick for Windows Dockerfile

---

jenkins/shared-library/vars/nightlyBuildPipeline.groovy
jenkins/shared-library/vars/weeklyBuildPipeline.groovy

problem: nightly and weekly jobs pass the branch name ci job when it is not needed.
The CI job ignores the branch name, which leads to many warnings in the Jenkins logs.
solution: do not pass the branch name to the CI jobs.

[jenkins] fix: nightly and weekly jobs passes the branch name ci job

---

client/catapult/CMakeGlobalSettings.cmake

problem: GCC on Ubuntu 24.04 updated the default _FORTIFY_SOURCE to 3
This causes refined warning when building catapult release
solution: update the _FORTIFY_SOURCE=3

[client/catapult] fix: update _FORTIFY_SOURCE=3 for gcc on Ubuntu 24.04

---

client/catapult/resources/config-node.properties
client/catapult/src/catapult/cache_db/RocksDatabase.cpp
client/catapult/src/catapult/config/NodeConfiguration.cpp
client/catapult/src/catapult/config/NodeConfiguration.h
client/catapult/tests/catapult/config/CatapultConfigurationTests.cpp
client/catapult/tests/catapult/config/NodeConfigurationTests.cpp

problem: RocksDB logs files use a lot of disk space
solution: allow node operator to limit log resource use

[client/catapult]: add configuration for managing RockDB log files

---

sdk/javascript/package.json

problem: git repo and homepage URL are not set in the package.json
solution: set the git repo and homepage URL in package.json

[sdk/javascript] fix: set the git repo and homepage URL

---

sdk/javascript/src/NetworkTimestamp.js
sdk/javascript/test/NetworkTimestamp_spec.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py
sdk/python/tests/test_NetworkTimestamp.py

problem: '| 0' is a bitwise operation that only works with signed 32-bit integers
since DateTime timestamps are larger, it is inappropriate for these numbers
solution: use Math.trunc instead, which properly handles larger numbers

[sdk/javascript]: '| 0' truncation trick doesn't work with large integers

---

jenkins/catapult/jenkins/catapult-client-build-base-image.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project.groovy
jenkins/catapult/jenkins/catapult-client-build-compiler-image.groovy
jenkins/catapult/jenkins/catapult-client-release-build.groovy

problem: in the prepare stage, the docker image names are created before the source code is checked out
this causes the docker image name to always be based on code in dev and not the build branch.
solution: checkout source code before creating the docker image name

[jenkins] fix: move checkout to the first step

---

client/catapult/CMakeGlobalSettings.cmake
jenkins/catapult/compilers/clang-latest.yaml
jenkins/catapult/compilers/clang-prior.yaml
jenkins/catapult/compilers/ubuntu-clang/Dockerfile

problem: tsan run is failing 'unexpected memory mapping'
this is due to a change in the latest Linux kernel.
solution: upgrade to the latest clang 18, which should have the fix
``https://github.com/google/sanitizers/issues/1716#issuecomment-2010399341``

[jenkins] fix: upgrade to clang 18

---

jenkins/catapult/baseImageDockerfileGenerator.py

problem: libzmq is failing to build on ARM due to 'avx' was removed in Clang 18
solution: only add the 'avx' options on intel architecture

[jenkins] fix: clang 18 remove the 'avx' options from ARM

---

sdk/javascript/README.md
sdk/javascript/package.json
sdk/javascript/scripts/run_catbuffer_generator.sh

problem: subpath exports are not working correctly with certain JS/TS environments
solution: for max compatibility, add 'import' and move 'default' last
add README for min TS requirements

[sdk/javascript]: fix package exports

---

linters/javascript/default.eslintrc

problem: no-resolved does not support subpath exports
solution: disable  no-resolved for symbol-sdk imports 
until ``https://github.com/import-js/eslint-plugin-import/issues/1810`` is resolved

[linters] fix: disable no-unresolved for symbol-sdk imports

---

jenkins/docker/fedora/javascript.Dockerfile
jenkins/docker/fedora/python.Dockerfile
jenkins/docker/ubuntu/java.Dockerfile
jenkins/docker/ubuntu/javascript.Dockerfile
jenkins/docker/ubuntu/linter.Dockerfile
jenkins/docker/ubuntu/python.Dockerfile
jenkins/shared-library/resources/buildEnvironment/baseImages.yaml

problem: docker images are not using the latest OS
solution: upgrade the base images to the latest
add zip and AWS CLI to the JS and Python images

[jenkins] fix: update docker images

---

jenkins/catapult/environment.py
jenkins/docker/ubuntu/java.Dockerfile
jenkins/docker/ubuntu/linter.Dockerfile

problem: in Python 3.12, shutil.rmtree onerror parameter is deprecated
solution: in Python 3.12 use onexc parameter instead of onerror

[jenkins] fix: linting failure due to rmtree onerror deprecation

---

client/catapult/docs/BUILD-docker.md
jenkins/catapult/compilers/fedora-gcc/Dockerfile
jenkins/catapult/compilers/ubuntu-clang/Dockerfile
jenkins/catapult/compilers/ubuntu-gcc/Dockerfile
jenkins/catapult/templates/RunTest.yaml
jenkins/catapult/templates/RunTestWindows.yaml
jenkins/catapult/versions.properties
jenkins/docker/ubuntu/cpp.Dockerfile

problem: catapult is not using the latest Fedora, Ubuntu and MongoDB versions
solution: update catapult docker images to use the latest.

[jenkins] fix: upgrade catapult os and mongodb version

---

sdk/javascript/src/nem/TransactionFactory.js
sdk/javascript/src/symbol/TransactionFactory.js
sdk/javascript/test/nem/TransactionFactory_spec.js
sdk/javascript/test/symbol/TransactionFactory_spec.js
sdk/javascript/test/test/basicTransactionFactoryTests.js
sdk/python/symbolchain/nem/TransactionFactory.py
sdk/python/symbolchain/symbol/TransactionFactory.py
sdk/python/tests/symbol/test_TransactionFactory.py
sdk/python/tests/test/BasicTransactionFactoryTest.py

[sdk/python]: add deserialize function to TransactionFactory in sdk
problem: deserialize is difficult to discover because it is only on model factory
solution: expose deserialize on sdk TransactionFactory too
[sdk/javascript]: add deserialize function to TransactionFactory in sdk
problem: deserialize is difficult to discover because it is only on model factory
solution: expose deserialize on sdk TransactionFactory too

[sdk]:  add deserialize function to TransactionFactory in sdk

---

sdk/javascript/README.md
sdk/javascript/examples/readme/nem.js
sdk/javascript/examples/readme/symbol.js
sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js

problem: using typed descriptors requires some extra knowledge
in order to create valid transactions
solution: simplify usage by adding helper functions to facades

[sdk/javascript]: extend facades to simplify usage of typed descriptors

---

jenkins/shared-library/vars/configureArtifactRepository.groovy
jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/githubHelper.groovy
jenkins/shared-library/vars/helper.groovy
jenkins/shared-library/vars/publish.groovy

problem: currently, Jenkins publishes artifacts to a Nexus repo without knowing its visibility
solution: Jenkins will now publish private GitHub repos to a private Nexus repo

[jenkins] fix: add support to publish artifacts to Nexus public and private repo base on GitHub repo visibility

---

jenkins/catapult/jenkins/catapult-client-build-catapult-project-daily.groovy
jenkins/catapult/jenkins/catapult-client-build-catapult-project-weekly.groovy

problem: catapult jobs will get updated when build configuration changes.
this causes catapult project jobs to fail due to defaults values are not set.
solution: set the default values for each parameter for the catapult project.

[jenkins] fix: catapult project fails on initial create

---

sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/symbolchain/facade/NemFacade.py
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py

[sdk/python]: add create_account to facades
problem: deriving an address from a private key is a multistep process
solution: add facade function that will derive public key and address from private key
[sdk/javascript]: add createAccount to facades
problem: deriving an address from a private key is a multistep process
solution: add facade function that will derive public key and address from private key

[sdk]: add createAccount to facades

---

jenkins/shared-library/vars/defaultCiPipeline.groovy
jenkins/shared-library/vars/gitPullRequestPipeline.groovy
jenkins/shared-library/vars/githubHelper.groovy

problem: some projects install packages from GitHub directly and do not have access
solution: create a GitHub token during lint setup where most packages are installed

[jenkins] fix: create a GitHub token for package install

---

jenkins/docker/fedora/javascript.Dockerfile
jenkins/docker/ubuntu/javascript.Dockerfile
jenkins/docker/windows/javascript.Dockerfile

problem: some Python projects use Javascript image since npm is required
solution: add coverage tool to Javascript image to allow Python projects to create code coverage

[jenkins] fix: add coverage to JavaScript image

---

sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/javascript/test/nem/MessageEncoder_spec.js
sdk/javascript/test/symbol/MessageEncoder_spec.js
sdk/javascript/test/test/messageEncoderTests.js
sdk/python/symbolchain/facade/NemFacade.py
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/symbolchain/nem/MessageEncoder.py
sdk/python/symbolchain/symbol/MessageEncoder.py
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py
sdk/python/tests/test/BasicMessageEncoderTest.py

[sdk/python]: add message_encoder to account classes
problem: user needs to know about MessageEncoder to encrypt/encode messages
solution: add a helper function to accounts to create it to improve discoverability
[sdk/javascript]: add messageEncoder to account classes
problem: user needs to know about MessageEncoder to encrypt/encode messages
solution: add a helper function to accounts to create it to improve discoverability

[sdk]: add message-encoder to account class 

---

sdk/javascript/src/symbol/index.js
sdk/javascript/src/symbol/metadata.js
sdk/javascript/test/symbol/metadata_spec.js
sdk/python/symbolchain/symbol/Metadata.py
sdk/python/tests/symbol/test_Metadata.py

[sdk/python]: add metadata_generate_key
problem: there is no built in way to convert a string to a metadata key
solution: add metadata_generate_key and make it compatible with SDK V2 implementation
[sdk/javascript]: add metadataGenerateKey
problem: there is no built in way to convert a string to a metadata key
solution: add metadataGenerateKey and make it compatible with SDK V2 implementation

[sdk]: add metadata-generate-key

---

sdk/javascript/src/symbol/Network.js
sdk/javascript/test/symbol/Network_spec.js
sdk/python/symbolchain/symbol/Network.py
sdk/python/tests/symbol/test_Network.py

[sdk/python]: add additional Symbol address utilities
problem: some useful functions from the SDK V2 are missing
solution: add missing functions:
- create address alias from namespace id
- extract namespace id from address alias
- create address from decoded address hex string (REST format)
[sdk/javascript]: add additional Symbol address utilities
problem: some useful functions from the SDK V2 are missing
solution: add missing functions:
- create address alias from namespace id
- extract namespace id from address alias
- create address from decoded address hex string (REST format)

[sdk]: add additional Symbol address utilities

---

linters/scripts/lint_indents.sh

problem: space indentation is recommended for rst files
generated rst files are space indented
solution: skip tab indentation check for rst files

[linters]: allow space indentation in reStructuredText files

---

jenkins/shared-library/vars/githubHelper.groovy
jenkins/shared-library/vars/helper.groovy

problem: the curl command is failing on Windows due to multiple issues
1. Windows cmd shell does not use backslash for multi-line command
2. in the curl write-out format the % was getting removed
solution: 1. use StringBuilder to format the curl command
2. remove the write-out option curl will return failure to shell

[jenkins] fix: curl command failing on Windows

---

.github/buildConfiguration.yaml
jenkins/shared-library/vars/monorepoControllerPipeline.groovy

problem: the linter job does not run on every commit which leads
to lint errors getting committed to dev.
solution: allow a Jenkins job to run on every commit.

[jenkins] fix: allow a Jenkins job to run on every commit

---

.github/jenkinsfile/cloneSymbolBranches.groovy
jenkins/shared-library/vars/githubHelper.groovy

problem: private repo failing to clone repo due to the GitHub token does not have permissions
this happens when there are a lot of Jenkins jobs that reuse worker nodes but not
in the same org(esp during the nightly builds)
solution: limit the GitHub token to the org since the GitHub token is org-specific.
also, only configure Git for push/PR.

[jenkins] fix: GitHub commands only requires the token

---

client/catapult/vcpkg.json

This PR introduces only bump `boost-modular-build-helper` to version 1.84.0 to solve an issue surfaced [after release VS 2022 >= 17.10](https://github.com/microsoft/vcpkg/issues/38980).
The component is only ancillary to vcpkg builds and does not impact managed code in any way.

[build] vcpkg patch for VS >= 17.10

---

sdk/javascript/package-lock.json

problem: missed updating the package version in the lock file
solution: update the package version in the lock file

[sdk/javascript] fix: missed updating version in the package-lock.json

---

client/rest/src/routes/routeUtils.js
client/rest/test/routes/routeUtils_spec.js

problem: there is no way to easily send a JSON object that bypasses the formatting subsystem
solution: add routeUtils.sendJson

[client/rest]: add routeUtils.sendJson

---

client/rest/resources/rest.json
client/rest/src/index.js
client/rest/src/plugins/routeSystem.js
client/rest/test/plugins/routeSystem_spec.js

problem: architecture assumes a single set of sdk (transaction) plugins and route plugins
solution: add separate 'routeExtensions' configuration
in order to allow route plugins to be a superset of sdk plugins
add placeholder for route-only plugin (rosetta)

[client/rest]: add route-only plugins

---

client/rest/src/db/CatapultDb.js
client/rest/src/routes/routeUtils.js
client/rest/test/db/CatapultDb_spec.js
client/rest/test/routes/routeUtils_spec.js

problem: addressToPublicKey only supports a single address and is not used
solution: replace it with lookupPublicKeys and support multiple addresses

[client/rest]: replace unused addressToPublicKey with lookupPublicKeys

---

sdk/javascript/src/facade/NemFacade.js
sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/NemFacade_spec.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/symbolchain/facade/NemFacade.py
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_NemFacade.py
sdk/python/tests/facade/test_SymbolFacade.py

[sdk/python]: add extract_signing_payload to facades
problem: there is no easy way to get signed data payload, which is needed to allow signing by hardware keys
solution: add extract_signing_payload to facades
[sdk/javascript]: add extractSigningPayload to facades
problem: there is no easy way to get signed data payload, which is needed to allow signing by hardware keys
solution: add extractSigningPayload to facades

[sdk]: add extract signing payload to facades

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/src/plugins/rosetta/constructionRoutes.js
client/rest/src/plugins/rosetta/rosetta.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js
client/rest/test/plugins/rosetta/constructionRoutes_spec.js

problem: data routes can benefit from response caching
solution: promote fetch helper from constructionRoutes to CatapultProxy
add caching support for repetitive data requests

[client/rest]: add CatapultProxy for caching responses

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js

problem: nemesis block is queried frequently
solution: cache it

[client/rest]: add nemesis block to CatapultProxy cache

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/src/plugins/rosetta/OperationParser.js
client/rest/src/plugins/rosetta/constructionRoutes.js
client/rest/src/plugins/rosetta/rosettaUtils.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js
client/rest/test/plugins/rosetta/OperationParser_spec.js
client/rest/test/plugins/rosetta/rosettaUtils_spec.js

[client/rest]: add additional utilities needed by data routes
problem: common logic in data routes should be refactored
solution: refactor and add new utilities
[client/rest]: fixes to OperationParser
problem: JSON used in tests is slightly different from REST JSON
solution: use REST JSON in tests and update implementation
[client/rest]: fixes to CatapultProxy
problem: pagination routes return object with data array, not array directly
solution: update fetchAll to extract data array
problem: bigint to hex string formatting drops leading zeros
solution: always return 16 character strings

[client/rest]: fixes to CatapultProxy and OperationParser and addition of more utilities for data routes

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js

problem: secondaryId should only be checked when primaryId is equal
solution: only check secondaryId when primaryId is equal

[client/rest]: fix ReceiptSource comparison in CatapultProxy

---

client/rest/src/plugins/rosetta/OperationParser.js
client/rest/test/plugins/rosetta/OperationParser_spec.js

problem: SDK JSON model 'fee' should be mapped to REST JSON model 'maxFee'
solution: add logic to convertTransactionSdkJsonToRestJson

[client/rest]: automatically map fee from SDK JSON model to REST JSON model

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js

[client/rest]: add postprocessing of epochAdjustment to CatapultProxy
problem: rosetta block route requires this value parsed
solution: parse and store parsed value in cache
[client/rest]: add missing await
problem: call to assertAsyncErrorThrown is missing await
solution: add await

[client/rest]: add postprocessing of epochAdjustment to CatapultProxy

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js
client/rest/test/plugins/rosetta/OperationParser_spec.js
client/rest/test/plugins/rosetta/constructionRoutes_spec.js
client/rest/test/plugins/rosetta/utils/rosettaTestUtils.js

problem: data route tests can reuse construction route tests utilities
solution: extract common routines into rosettaTestUtils

[client/rest]: refactor rosetta test utilities

---

client/rest/src/plugins/rosetta/OperationParser.js
client/rest/test/plugins/rosetta/OperationParser_spec.js

problem: OperationParser assumes all receipts have amount property
solution: check if amount property exists

[client/rest]: skip parsing of receipts without amounts

---

client/rest/src/plugins/rosetta/CatapultProxy.js
client/rest/test/plugins/rosetta/CatapultProxy_spec.js

problem: when multiple cache fill requests are made in parallel, properties will be parsed multiple times
solution: only parse first cache object returned

[client/rest]: workaround race condition in CatapultProxy

---

client/rest/src/plugins/rosetta/OperationParser.js
client/rest/src/plugins/rosetta/accountRoutes.js
client/rest/src/plugins/rosetta/blockRoutes.js
client/rest/src/plugins/rosetta/mempoolRoutes.js
client/rest/test/plugins/rosetta/OperationParser_spec.js
client/rest/test/plugins/rosetta/accountRoutes_spec.js
client/rest/test/plugins/rosetta/blockRoutes_spec.js
client/rest/test/plugins/rosetta/constructionRoutes_spec.js
client/rest/test/plugins/rosetta/mempoolRoutes_spec.js
client/rest/test/plugins/rosetta/utils/rosettaTestUtils.js

[rest/client]: don't return currency metadata from /account/balance
problem: mesh cli does deep compare of metadata and expects it to be unset
solution: clear metadata from route response
[rest/client]: operations returned by construction routes should not have operation status
problem: all operations have success operation status
solution: only return operations with operation status from data routes

[client/rest]: rosetta integration fixes after addition of data routes 

---

client/rest/src/plugins/rosetta/accountRoutes.js
client/rest/src/plugins/rosetta/constructionRoutes.js
client/rest/test/plugins/rosetta/accountRoutes_spec.js
client/rest/test/plugins/rosetta/constructionRoutes_spec.js

problem: resolved mosaic id should be specified in currency metadata
solution: update construction/parse to resolve 'currencyMosaicId' and set metadata
restore currency metadata in account/balance

[client/rest]: update rosetta to support id being set in currency metadata

---

client/rest/src/plugins/rosetta/nem/NemProxy.js
client/rest/src/plugins/rosetta/nem/constructionRoutes.js
client/rest/src/plugins/rosetta/nem/rosettaUtils.js
client/rest/src/plugins/rosetta/openApi/model/CurveType.js
client/rest/src/plugins/rosetta/rosettaUtils.js
client/rest/src/plugins/rosetta/symbol/CatapultProxy.js
client/rest/src/plugins/rosetta/symbol/accountRoutes.js
client/rest/src/plugins/rosetta/symbol/blockRoutes.js
client/rest/src/plugins/rosetta/symbol/constructionRoutes.js
client/rest/src/plugins/rosetta/symbol/mempoolRoutes.js
client/rest/src/plugins/rosetta/symbol/networkRoutes.js
client/rest/src/plugins/rosetta/symbol/rosettaUtils.js
client/rest/test/plugins/rosetta/nem/NemProxy_spec.js
client/rest/test/plugins/rosetta/nem/constructionRoutes_spec.js
client/rest/test/plugins/rosetta/nem/rosettaUtils_spec.js
client/rest/test/plugins/rosetta/nem/rosetta_spec.js
client/rest/test/plugins/rosetta/nem/utils/rosettaTestUtils.js
client/rest/test/plugins/rosetta/rosettaUtils_spec.js
client/rest/test/plugins/rosetta/symbol/CatapultProxy_spec.js
client/rest/test/plugins/rosetta/symbol/accountRoutes_spec.js
client/rest/test/plugins/rosetta/symbol/blockRoutes_spec.js
client/rest/test/plugins/rosetta/symbol/constructionRoutes_spec.js
client/rest/test/plugins/rosetta/symbol/mempoolRoutes_spec.js
client/rest/test/plugins/rosetta/symbol/networkRoutes_spec.js
client/rest/test/plugins/rosetta/symbol/rosettaUtils_spec.js
client/rest/test/plugins/rosetta/symbol/utils/rosettaTestUtils.js
client/rest/test/plugins/rosetta/utils/rosettaTestUtils.js

[client/rest]: add support for NEM /construction/derive
problem: start adding NEM construction routes
solution: add NEM /construction/derive
refactor shared Symbol and NEM test utilities
[client/rest]: promote shared NEM and Symbol rosetta utils
problem: all rosetta utils are under /symbol but some can be used by nem
solution: move shared utils up a level

[client/rest]: add support for NEM /construction/derive

---

client/rest/src/plugins/rosetta/symbol/OperationParser.js
client/rest/test/plugins/rosetta/symbol/OperationParser_spec.js

problem: weak comparison is treating zero as falsy
solution: check feeMultiplier against undefined

[client/rest]: properly handle fee calculation when block fee multiplier is zero

---

client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/src/plugins/rosetta/nem/accountRoutes.js
client/rest/src/plugins/rosetta/nem/blockRoutes.js
client/rest/src/plugins/rosetta/nem/networkRoutes.js
client/rest/src/plugins/rosetta/symbol/accountRoutes.js
client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js
client/rest/test/plugins/rosetta/nem/networkRoutes_spec.js
client/rest/test/plugins/rosetta/nem/utils/rosettaTestUtils.js

problem: small cleanup and refactoring identified during NEM rosetta route development
solution: use helper functions for /local/block/at requests (and test setup)
drop extra parameter passed to OperationParser.parseTransaction
minor renaming for consistency

[client/rest]: small cleanup after merging all NEM rosetta routes

---

jenkins/catapult/installDepsLocal.py

problem: clang is defaulting to older c++ standard
solution: specify c++ standard version to b2 explicitly

[jenkins]: localDepsLocal boost build is failing with clang

---

client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/test/plugins/rosetta/nem/OperationParser_spec.js

problem: mosaic transfer bags can be fractional, causing calculations to result in floating point values
solution: truncate calculated mosaic transfer amount derived from mosaic bags

[client/rest]: truncate mosaic transfer amount calculated from bag

---

client/rest/src/plugins/rosetta/nem/NemProxy.js
client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/src/plugins/rosetta/nem/blockRoutes.js
client/rest/src/plugins/rosetta/nem/rosettaUtils.js
client/rest/test/plugins/rosetta/nem/NemProxy_spec.js
client/rest/test/plugins/rosetta/nem/OperationParser_spec.js
client/rest/test/plugins/rosetta/nem/accountRoutes_spec.js
client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js
client/rest/test/plugins/rosetta/nem/constructionRoutes_spec.js
client/rest/test/plugins/rosetta/nem/mempoolRoutes_spec.js
client/rest/test/plugins/rosetta/nem/rosettaUtils_spec.js
client/rest/test/plugins/rosetta/nem/utils/rosettaTestUtils.js
client/rest/test/plugins/rosetta/symbol/OperationParser_spec.js

[client/rest]: update NEM rosetta to handle mosaic (re)definitions
problem: NEM mosaic (re)definition behavior is dependent on current state
solution: integrate 'mosaic/definition/supply' into mosaic definition creation
transaction processing
[client/rest]: in NEM rosetta use ':' as token separator to match NEM
problem: NEM uses ':' as mosaic name separator but rosetta implementation is using '.'
solution: use ':' as separator for consistency

[client/rest]: update NEM rosetta to handle mosaic (re)definitions

---

client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/src/plugins/rosetta/nem/rosettaUtils.js
client/rest/test/plugins/rosetta/nem/OperationParser_spec.js
client/rest/test/plugins/rosetta/nem/rosettaUtils_spec.js

problem: NEM allows multiple definitions of same mosaic in block, but only last one is relevant
solution: add postprocessing in parseBlock to debit earlier duplicate mosaic definitions

[client/rest]: NEM rosetta should only credit LAST unique mosaic definition in block

---

client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/test/plugins/rosetta/nem/OperationParser_spec.js

problem: some intermediate values can exceed Number.MAX_SAFE_INTEGER, leading to loss of precision
solution: use BitInt math and convert result to Number

[client/rest]: use 64-bit arithmetic when calculating transfer amounts

---

client/rest/src/plugins/rosetta/nem/NemProxy.js
client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/test/plugins/rosetta/nem/NemProxy_spec.js
client/rest/test/plugins/rosetta/nem/OperationParser_spec.js

problem: NIS /local/mosaic/definition/supply API was extended to include expirationHeight
solution: handle expirationHeight in NEM rosetta operation parser

[client/rest]: add handling for expirationHeight

---

jenkins/docker/windows/javascript.Dockerfile

problem: Javascript docker build fails on Windows
solution: remove invalid chars

[jenkins] fix: remove invalid chars

---

jenkins/catapult/runDockerBuild.py

problem: ABI for compilers is forward compatibility
solution: move compiler caching into a versioned folder

[jenkins] fix: create jenkins c++ versioned caching

---

jenkins/docker/ubuntu/linter.Dockerfile

problem: npm-groovy-lint 15.0.1 and greater fails to lint Jenkins groovy files
solution: stay with npm-groovy-lint@15.0.0 until the issue is fixed.
issue: ``https://github.com/nvuillam/npm-groovy-lint/issues/422``

[jenkins] fix: groovy failing linting with latest groovy lint

---

jenkins/catapult/baseImageDockerfileGenerator.py

problem: CI build for Fedora Conan image fails due to incorrect command
solution: update the Conan build stage to support Fedora

[catapult/client] fix: Fedora Conan build failing

---

jenkins/catapult/baseImageDockerfileGenerator.py

problem: rocksdb fails to build with GCC 12.3 due to an array-bounds error
solution: disable the warning for GCC 12

[jenkins] fix: rocksdb fails with gcc 12.3

---

jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/installDepsLocal.py

problem: starting with mongocxx r3.10.0, MSVC toolchain on Windows generates different library names
solution: disable this feature by setting ENABLE_ABI_TAG_IN_LIBRARY_FILENAMES=OFF

[jenkins] fix: mongo-cxx-driver libraries name change in r3.10

---

jenkins/catapult/process.py
jenkins/catapult/runDockerBuildInnerBuild.py

problem: building catapult deps fails on Windows due to an invalid UTF-8 character
solution: add exception handling

[jenkins] fix: fail to decode line on Windows

---

client/rest/src/plugins/rosetta/nem/OperationParser.js
client/rest/src/plugins/rosetta/nem/rosettaUtils.js
client/rest/test/plugins/rosetta/nem/OperationParser_spec.js
client/rest/test/plugins/rosetta/nem/rosettaUtils_spec.js

problem: prior to the mosaic redefinition fork, mosaic description changes are considered significant
solution: change comparison of mosaic definitions prior to fork

[client/rest]: add mosaic redefinition fork handling to rosetta implementation

---

jenkins/catapult/runDockerBuildInnerBuild.py

problem: latest version of Conan fails to set home path on Windows
solution: Conan now requires absolute path in the format of ``c:\conan``

[jenkins] fix: conan fails to set home path on Windows

---

jenkins/catapult/runDockerBuild.py
jenkins/catapult/runDockerBuildInnerPrepare.py

problem: catapult release image uses the default working directory from the base image.
user might not have permissions to this folder.
solution: set the default working directory to the catapult user path

[jenkins] fix: unable to run catapult tools from release image

---

sdk/javascript/scripts/ci/build.sh

problem: rustc 1.82.0 seems to break wasm-opt
solution: downgrade to rustc 1.81.0 for now.

[sdk/javascript] fix: wasm-opt failing with rustc 1.82.0

---

jenkins/docker/windows/javascript.Dockerfile
jenkins/docker/windows/python.Dockerfile

problem: Windows docker image for Python and JavaScript is failing with Python 3.13.0
solution: Use the default pip installs with Python 3.13.0

[jenkins] fix: pip upgrade fails with Python 3.13.0

---

jenkins/catapult/process.py
jenkins/catapult/runDockerBuild.py

problem: multiple level of dispatch_subprocess causing build to fail with invalid char.
set the decode() to ignore invalid chars and remove try..catch.
solution: ignore the invalid chars on decode error

[jenkins] fix: ignore invalid chars during build

---

jenkins/catapult/versions.properties
jenkins/shared-library/resources/buildEnvironment/baseImages.yaml

problem: automation is not using the latest Python release
solution: update the automation to use Python 3.13 for Ubuntu latest release

[jenkins] fix: add Python 3.13 to build

---

sdk/javascript/wasm/Cargo.toml

problem: wasm-bindgen no longer works with feature resolver version 1
solution: update the edition to 2021 which uses resolver version 2
bug: ``https://github.com/rustwasm/wasm-bindgen/issues/4304``
resolution: https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html

[sdk/javascript] fix: update the rust edition to 2021

---

sdk/javascript/src/facade/SymbolFacade.js
sdk/javascript/test/facade/SymbolFacade_spec.js
sdk/python/symbolchain/facade/SymbolFacade.py
sdk/python/tests/facade/test_SymbolFacade.py

[sdk/python] fix: add a cosign_transaction_hash
problem: no capability to sign the transaction hash
solution: add a cosign_transaction_hash()
[sdk/javascript] fix: add a cosignTransactionHash
problem: no capability to sign the transaction hash
solution: add a cosignTransactionHash()

[sdk]: add a cosign transaction hash

---

sdk/python/pyproject.toml

problem: cryptography 44.0.0 does not support python 3.9.0 and 3.9.1
Poetry fails to published the package.
solution: update Python minimum version requirements to 3.9.2
```
13:45:00  + poetry add cryptography~=44.0.0
13:45:10  Creating virtualenv symbol-sdk-python-Q2sVR_aH-py3.10 in /home/ubuntu/.cache/pypoetry/virtualenvs
13:45:13  
13:45:13  Updating dependencies
13:45:13  Resolving dependencies...
13:45:13  
13:45:13  The current project's Python requirement (>=3.9,<4.0) is not compatible with some of the required packages Python requirement:
13:45:13    - cryptography requires Python !=3.9.0,!=3.9.1,>=3.7, so it will not be satisfied for Python 3.9 || 3.9.1
13:45:13  
13:45:13  Because no versions of cryptography match >44.0.0,<44.1.0
13:45:13   and cryptography (44.0.0) requires …
```

[sdk/python] fix: update Python minimum version requirements to 3.9.2

---

jenkins/shared-library/vars/publish.groovy

problem: The latest Transifex CLI uses a token instead of a username/password
solution: update the publish to get an API token

[jenkins] fix: latest Transifex CLI requires a token

---

jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/installDepsLocal.py

problem: Boost update their download URI
solution: update the Boost URI for the image build
https://github.com/boostorg/boost/issues/843#issuecomment-2567034014

[jenkins] fix: boost download URI update

---

jenkins/docker/ubuntu/java.Dockerfile

problem: there is no gradle tool in Java image
solution: add Gradle to the Java docker image

[jenkins] fix: add Gradle to the Java docker image

---

jenkins/shared-library/vars/monorepoControllerPipeline.groovy

problem: in some instances, Jenkin(controller) thinks no job needs to be run
this seems to be the case, especially on rebase.
solution: run all jobs when none is found.

[jenkins] fix: Jenkins no jobs run

---

jenkins/catapult/templates/RunTest.yaml
jenkins/catapult/templates/RunTestWindows.yaml
jenkins/docker/ubuntu/cpp.Dockerfile
jenkins/docker/ubuntu/javascript.Dockerfile

problem: not using the latest MongoDB in testing
solution: upgrade to MongoDB 8

[jenkins] fix: upgrade tests to use MongoDB 8

---

sdk/javascript/scripts/ci/build.sh
sdk/javascript/wasm/Cargo.toml

problem: the latest version of hex-literal requires edition2024 feature
solution: upgrade to rustc 1.85, which supports edition2024 feature

[sdk/javascript] fix: upgrade rustc to supports edition2024 feature

---

client/rest/Dockerfile

problem: Docker Scout reports issues with REST image such as no default Non-Root User
solution: upgrade to Ubuntu 24.04, which has a non-root user

[client/rest] fix: some issues reported by docker scout

---

jenkins/docker/ubuntu/python.Dockerfile
jenkins/shared-library/resources/buildEnvironment/baseImages.yaml

problem: openssl command is failing on Ubuntu 24.10
solution: revert to Ubuntu 24.04 LTS and install Python 3.13 from Deadsnakes PPA

[jenkins] fix: openssl fails on Ubuntu 24.10

---

catbuffer/schemas/nem/block.cats

problem: previous_block_hash schema missing the object size
solution: update to type to SizePrefixedHash256

[catbuffer/schemas]: fix NEM block previous_block_hash schema

---

client/rest/src/db/CatapultDb.js
client/rest/test/db/CatapultDb_spec.js
client/rest/test/db/utils/dbTestUtils.js

problem: catapultDB created an incorrect network, which caused the address from publicKey to be incorrect
this caused search by publicKey to create an incorrect address, which would fail.
solution: create the network correctly

[client/rest] fix: catapultdb initialized with incorrect network

---

jenkins/catapult/baseImageDockerfileGenerator.py
jenkins/catapult/compilers/debian-gcc/Dockerfile
jenkins/catapult/compilers/fedora-gcc/Dockerfile
jenkins/catapult/compilers/ubuntu-clang/Dockerfile
jenkins/catapult/compilers/ubuntu-gcc/Dockerfile
jenkins/catapult/jenkins/catapult-client-build-base-image.groovy
jenkins/catapult/jenkins/catapult-client-build-compiler-image.groovy
jenkins/catapult/jenkins/catapult-client-prepare-base-image.groovy
jenkins/catapult/jenkins/catapult-client-release-build.groovy
jenkins/catapult/runDockerBuild.py
jenkins/catapult/templates/FedoraTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuReleaseBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestBaseImage.Dockerfile
jenkins/catapult/templates/UbuntuTestSanitizerBaseImage.Dockerfile
jenkins/catapult/templates/release.Dockerfile
jenkins/shared-library/vars/dockerHelper.groovy

problem: catapult docker images do not have supply chain attestations
solution: add docker buildx with supply chain attestations enabled by default
create a release Dockerfile to build a release image

[jenkins]: add catapult image supply chain attestations for docker build

---

jenkins/docker/ubuntu/javascript.Dockerfile

problem: Javascript image does not support node-canvas module
solution: install node-canvas dependencies during Javascript image creation

[jenkins] fix: install node-canvas dependencies in Javascript image
