catbuffer/schemas/nem/mosaic/mosaic_definition.cats, sdk/python/symbolchain/nc/__init__.py
=> fix(catbuffer/schemas): spelling mistake (Verfiable => Verifiable)

catbuffer/parser/Jenkinsfile, client/rest/Jenkinsfile, jenkins/Jenkinsfile, jenkins/docker/javascript.Dockerfile, jenkins/docker/linter.Dockerfile, jenkins/docker/python.Dockerfile, jenkins/shared-library/vars/defaultCiPipeline.groovy, linters/Jenkinsfile, sdk/javascript/Jenkinsfile, sdk/python/Jenkinsfile, sdk/python/scripts/ci/setup_test.sh
=> [jenkins] feature: run CI pipeline in docker

jenkins/docker/javascript.Dockerfile, jenkins/docker/linter.Dockerfile, jenkins/docker/python.Dockerfile, jenkins/shared-library/vars/verifyCommitMessage.groovy, linters/git/.gitlint, linters/scripts/run_gitlint.sh
- add gitlint to all CI docker images
- add custom gitlint configuration
=> [linters]: enable gitlint

sdk/javascript/src/utils/converter.js, sdk/javascript/test/utils/converter_spec.js
bytesToBigInt and intFromBytes
=> [sdk/javascript] subtask: add helper functions 

.github/workflows/codeql-analysis.yaml
Enable Codeql for Python and JavaScript for testing.  If looks good then will enable for cpp.
=> feat: Enable Codeql for Python and JavaScript

sdk/python/generator/PodTypeFormatter.py, sdk/python/generator/StructTypeFormatter.py, sdk/python/generator/TypeFormatter.py, sdk/python/generator/printers.py, sdk/python/symbolchain/ArrayHelpers.py, sdk/python/symbolchain/BaseValue.py, sdk/python/symbolchain/nc/__init__.py, sdk/python/symbolchain/sc/__init__.py, sdk/python/tests/nem/test_TransactionFactory.py, sdk/python/tests/test_BaseValue.py
align with javascript sdk behavior
=> [sdk/python] task: replace BaseValue clamping with bounds checking

README.md
- add relative links to code
- add links to jenkins
- add coverage badges and links
=> [monorepo] task: update readme

sdk/javascript/src/RuleBasedTransactionFactory.js, sdk/javascript/src/TransactionDescriptorProcessor.js, sdk/javascript/test/RuleBasedTransactionFactory_spec.js, sdk/javascript/test/TransactionDescriptorProcessor_spec.js, sdk/python/symbolchain/RuleBasedTransactionFactory.py, sdk/python/tests/test_RuleBasedTransactionFactory.py, sdk/python/tests/test_TransactionDescriptorProcessor.py
port TransactionDescriptorProcessor and RuleBasedTransactionFactory
=> [sdk/javascript] add common TransactionFactory code

client/rest/test/catapult-sdk/utils/arrayUtils_spec.js, sdk/javascript/src/utils/BufferView.js, sdk/javascript/src/utils/Writer.js, sdk/javascript/src/utils/arrayHelpers.js, sdk/javascript/test/utils/BufferView_spec.js, sdk/javascript/test/utils/Writer_spec.js, sdk/javascript/test/utils/arrayHelpers_spec.js
=> [sdk/javascript] reader writer

README.md, catbuffer/parser/Jenkinsfile, catbuffer/parser/dev_requirements.txt, catbuffer/parser/scripts/ci/setup_lint.sh, catbuffer/parser/scripts/ci/setup_test.sh, catbuffer/parser/scripts/ci/test.sh, client/rest/Jenkinsfile, client/rest/package-lock.json, client/rest/package.json, client/rest/scripts/ci/test.sh, codecov.yaml, codecov.yml, jenkins/docker/javascript.Dockerfile, jenkins/docker/python.Dockerfile, jenkins/shared-library/vars/codeCoverage.groovy, jenkins/shared-library/vars/defaultCiPipeline.groovy, jenkins/shared-library/vars/runScript.groovy, jenkins/shared-library/vars/runTests.groovy, sdk/javascript/.nycrc.yaml, sdk/javascript/Jenkinsfile, sdk/javascript/package.json, sdk/javascript/scripts/ci/test.sh, sdk/javascript/scripts/ci/test_vectors.sh, sdk/python/.coveragerc, sdk/python/Jenkinsfile, sdk/python/scripts/ci/test.sh, sdk/python/scripts/ci/test_examples.sh, sdk/python/scripts/ci/test_vectors.sh
Add automatic code coverage upload to codecov.  PR will fail if the code coverage falls below the minimum configured value for the feature.
=> [monorepo] feat: Add code coverage upload

jenkins/shared-library/vars/createMultibranchJob.groovy, jenkins/shared-library/vars/defaultCiPipeline.groovy
Linters and Jenkins folder is shared across monorepos.  The Jenkins job needs to check out submodule to get access to the Dockerfile to run the pipeline.
=> [monorepo] feat: checkout submodule

client/rest/package-lock.json, client/rest/package.json, sdk/javascript/package-lock.json, sdk/javascript/package.json
there are dependendabot warnings in client/rest and sdk/javascript.
updated package versions
yes
=> [monorepo] build: update dependencies and fix dependabot warnings

sdk/javascript/CHANGELOG.md, sdk/javascript/README.md, sdk/javascript/package.json, sdk/javascript/src/index.js
(default pull request is not applicable here)
=> [sdk/javascript] task: package preparations

.github/dependabot.yaml, client/rest/package-lock.json, client/rest/package.json, sdk/javascript/package-lock.json, sdk/javascript/package.json
Dependabot flagged out of date dependencies but missed some.
Dependencies need to be updated.
Updated dependencies and fixed inspection of sdk/javascript.
yes
=> [monorepo]: update dependencies

sdk/python/CHANGELOG.md, sdk/python/pyproject.toml
=> [sdk/python]: bump version, updated changeleg

.github/dependabot.yaml, sdk/javascript/package-lock.json, sdk/javascript/package.json, sdk/python/requirements.txt
This PR was created by the Combine PRs action by combining the following PRs:
* #164 build(deps-dev): bump yargs from 17.3.1 to 17.4.0 in /sdk/javascript
* #163 build(deps): bump pyzbar from 0.1.8 to 0.1.9 in /sdk/python
* #162 build(deps): bump cryptography from 36.0.1 to 36.0.2 in /sdk/python
=> Update combined dependencies

client/rest/package-lock.json, client/rest/package.json, sdk/javascript/package-lock.json, sdk/javascript/package.json, sdk/python/requirements.txt
stale dependencies detected by dependabot
updated dependencies 
jenkins
=> [monorepo]: update other outdated dependencies

jenkins/docker/postgres.Dockerfile
Unable to run applications with postgres tests
There is no docker image with postgres
Created a postgres Dockerfile since it is easier to maintain and less bloating of the images.
Yes
=> [monorepo] task: add postgres dockerfile

jenkins/shared-library/vars/codeCoverage.groovy, jenkins/shared-library/vars/defaultCiPipeline.groovy
There is no support for Java code coverage.
Java code coverage is not getting verified.
Jacoco option is added to verify the code coverage meets what is configured in the pom.xml
=> [monorepo] task: add jacoco support

catbuffer/schemas/symbol/state/restriction_account_types.cats, catbuffer/schemas/symbol/statements/address_resolution_statement.cats, catbuffer/schemas/symbol/statements/mosaic_resolution_statement.cats
problem: some cats files are not self contained
solution: add missing imports
issue: #276
=> [catbuffer/schemas]: make all cats files self-contained

sdk/javascript/src/Bip32.js, sdk/javascript/test/Bip32_spec.js, sdk/python/symbolchain/Bip32.py, sdk/python/tests/test_Bip32.py
problem: sdk cannot generate seed phrase
solution: add Bip32.random
=> [sdk]: add helper function for generating random mnemonics

sdk/javascript/src/symbol/MerkleHashBuilder.js, sdk/javascript/test/symbol/MerkleHashBuilder_spec.js, sdk/python/symbolchain/symbol/MerkleHashBuilder.py, sdk/python/tests/symbol/test_MerkleHashBuilder.py
[sdk/python]: add prove_merkle for performing merkle tree proofs
problem: sdk does not provide functionality for validating merkle tree proofs
solution: add missing functionality
[sdk/javascript]: add proveMerkle for performing merkle tree proofs
problem: sdk does not provide functionality for validating merkle tree proofs
solution: add missing functionality
=> [sdk]: add support for performing merkle tree proofs

sdk/javascript/src/impl/CipherHelpers.js, sdk/javascript/src/nem/MessageEncoder.js, sdk/javascript/src/symbol/MessageEncoder.js, sdk/javascript/test/nem/MessageEncoder_spec.js, sdk/javascript/test/symbol/MessageEncoder_spec.js, sdk/javascript/test/test/messageEncoderTests.js, sdk/javascript/test/test/sharedKeyTests.js
message encoder is a helper around encrypted (and encoded) messages
This is continuation/port of #340
=> [sdk/javascript]: add MessageEncoder

sdk/javascript/package-lock.json, sdk/javascript/package.json, sdk/javascript/scripts/ci/build.sh, sdk/javascript/webpack.config.js
problem: sdk assumes nodejs environment and cannot be used directly in browser
solution: use webpack to create browser compatable sdk bundle
=> [sdk/javascript]: add webpack for creating bundled sdk js for browser

client/rest/package-lock.json, client/rest/package.json, client/rest/src/catapult-sdk/index.js, client/rest/src/catapult-sdk/utils/CachedFileLoader.js, client/rest/src/plugins/mosaic/supplyRoutes.js, client/rest/src/routes/networkRoutes.js, client/rest/test/catapult-sdk/utils/CachedFileLoader_spec.js, client/rest/test/plugins/mosaic/supplyRoutes_spec.js, client/rest/test/routes/networkRoutes_spec.js
problem: network routes reload and reprocess server config files each GET
solution: cache parsed results
=> [sdk/javascript]: add caching of configuration files

jenkins/shared-library/vars/defaultCiPipeline.groovy, jenkins/shared-library/vars/nightlyBuildPipeline.groovy
Jenkins jobs are failing in certain scenario.
1. Manual Multibranch PR job is failing to checkout the source 
2. Nightly job fails if a job is found but not in the build configuration file.
1. Multibranch job only configure the git remote for the current branch.  There is no need to checkout the source on a manual job.
2. Nightly job will verify that a job is in the build configuration file before adding to the list of jobs to run
=> [jenkins] fix: Jenkins job failure

jenkins/docker/java.Dockerfile, jenkins/docker/javascript.Dockerfile, jenkins/docker/linter.Dockerfile, jenkins/docker/postgres.Dockerfile, jenkins/docker/python.Dockerfile
Dockerfile are not using the latest Ubuntu image version
Update Dockerfile to use the latest Ubuntu image
On my dev box
=> [jenkins] fix: update dockerfile to latest base image

.github/buildConfiguration.yaml, jenkins/catapult/jenkins/catapult-client-build-base-image-all.groovy, jenkins/catapult/jenkins/catapult-client-build-catapult-project-daily.groovy, jenkins/catapult/jenkins/catapult-client-build-catapult-project-weekly.groovy, jenkins/catapult/jenkins/catapult-client-build-compiler-image-all.groovy, jenkins/shared-library/vars/createMonorepoMultibranchJobs.groovy, jenkins/shared-library/vars/createMonorepoPipelineJobs.groovy, jenkins/shared-library/vars/createMultibranchJob.groovy, jenkins/shared-library/vars/createPipelineJob.groovy, jenkins/shared-library/vars/monorepoSeedPipeline.groovy
All pipeline jobs were created in Jenkins manually
Add custom build configuration for pipeline jobs which allow the jobs to be created from a git.
Running in Jenkins.
=> [jenkins] feat: add custom build configuration

sdk/python/examples/docs/__main__.py, sdk/python/examples/docs/__main__.py.tmpl
Docs are using one of testnet nodes. Should use reference node. 
Change docs examples t use reference node (reference.symboltest.net)
=> [sdk/python] docs: update reference node

sdk/javascript/README.md, sdk/javascript/examples/readme/nem.js, sdk/javascript/examples/readme/symbol.js, sdk/javascript/scripts/ci/test_examples.sh, sdk/python/README.md, sdk/python/examples/readme/nem.py, sdk/python/examples/readme/symbol.py, sdk/python/scripts/ci/test_examples.sh
Rewrite readmes and check working examples
=> [sdk]: rewrite SDK readmes

sdk/javascript/README.md, sdk/javascript/package.json, sdk/javascript/src/index.js
- update readme with usage examples
- update packaging
[sdk/javascript]: bundle version - make both transaction factories visible (otherwise static methods aren't visible inside facade)
=> [sdk/javascript]: finalize release preparation

sdk/javascript/package-lock.json, sdk/javascript/package.json
update crypto-wasm-node dependency to 0.1.1 for the javascript sdk.
=> [sdk/javascript] fix: update crypto-wasm-node to 0.1.1

catbuffer/parser/tests/test_AstPostProcessor.py
=> fix: typo in test_AstPostProcessor.py

catbuffer/schemas/nem/multisig/multisig.cats, catbuffer/schemas/nem/transaction_type.cats, sdk/javascript/src/nem/TransactionFactory.js, sdk/javascript/src/nem/models.js, sdk/javascript/src/symbol/TransactionFactory.js, sdk/javascript/test/nem/TransactionFactory_spec.js, sdk/javascript/test/symbol/TransactionFactory_spec.js, sdk/python/symbolchain/nc/__init__.py, sdk/python/symbolchain/nem/TransactionFactory.py, sdk/python/symbolchain/symbol/TransactionFactory.py, sdk/python/tests/nem/test_TransactionFactory.py, sdk/python/tests/symbol/test_TransactionFactory.py
f(type, version) => friendly name
requested by community
=> [sdk]: add function for looking up friendly transaction name given type and version

jenkins/shared-library/vars/buildCode.groovy, jenkins/shared-library/vars/helper.groovy, jenkins/shared-library/vars/publish.groovy, jenkins/shared-library/vars/runTests.groovy
Publishing a package is not customizable by each project.
Projects can only publish one artifact from each project.
A project can provide a publishing script that will allow custom steps to publish an artifact.
Testing in Jenkins
=> [jenkins]: Add a custom publish script

jenkins/shared-library/vars/defaultCiPipeline.groovy
problem: currently, vector tests are not run by default.
solution: always run vector tests
=> [jenkins] fix: always run the vector tests

client/rest/package-lock.json, client/rest/package.json, client/rest/src/db/CatapultDb.js, client/rest/test/db/dbUtils_spec.js, client/rest/test/db/utils/dbTestUtils.js, client/rest/test/routes/dbFacade_spec.js, client/rest/test/testUtils.js
problem: there are some breaking changes
solution: update rest code
=> [client/rest]: upgrade mongodb to 6.3

client/catapult/CMakeGlobalSettings.cmake, client/catapult/src/catapult/ionet/PacketHeader.h, client/catapult/tests/catapult/utils/CatapultExceptionTests.cpp, jenkins/catapult/compilers/clang-latest.yaml, jenkins/catapult/compilers/clang-prior.yaml
problem: clang compiler is outdated
solution: upgrade clang compiler
prior upgraded from v14 -> v16
latest upgraded from v15 -> v17
=> [client/catapult] fix: upgrade clang compiler to latest

.github/workflows/codeql-analysis.yaml
problem: CodeQL is not running with the latest configuration
solution: update CodeQL workflow to the latest
=> [monorepo] fix: updated the CodeQL action

jenkins/docker/fedora/javascript.Dockerfile, jenkins/docker/fedora/python.Dockerfile, jenkins/infra/jenkins/build-ci-image-all.groovy, jenkins/infra/jenkins/build-ci-image.groovy, jenkins/shared-library/resources/buildEnvironment/baseImages.yaml, sdk/javascript/Jenkinsfile, sdk/python/Jenkinsfile
problem: there is no support for building and testing on Fedora.
solution: add Fedora CI images for testing
=> [jenkins] feat: add support for build and test on Fedora

jenkins/catapult/baseImageDockerfileGenerator.py, jenkins/docker/ubuntu/cpp.Dockerfile
problem: some pip packages were installed as root in the virtual environment.
This led to the package not found.
solution: run all pip installs as non-root user
=> [jenkins] fix: incorrect premission python virtual environment

sdk/javascript/generator/AbstractTypeFormatter.py, sdk/javascript/generator/FactoryFormatter.py, sdk/javascript/generator/Generator.py, sdk/javascript/generator/StructTypeFormatter.py, sdk/javascript/generator/TypeFormatter.py, sdk/javascript/src/nem/models.js, sdk/javascript/src/symbol/models.js
problem: generated code is very duplicative
solution: add concept of base class to generator to reduce duplication
=> [sdk/javascript]: improve codegen to significantly reduce size of generated models

sdk/python/generator/AbstractTypeFormatter.py, sdk/python/generator/EnumTypeFormatter.py, sdk/python/generator/FactoryFormatter.py, sdk/python/generator/Generator.py, sdk/python/generator/StructTypeFormatter.py, sdk/python/generator/TypeFormatter.py, sdk/python/symbolchain/nc/__init__.py, sdk/python/symbolchain/sc/__init__.py
problem: generated code is very duplicative
solution: add concept of base class to generator to reduce duplication
=> [sdk/python]: improve codegen to significantly reduce size of generated models

jenkins/shared-library/vars/publish.groovy
problem: git helper function to their own file, but some ref was not updated
solution: update the git function to the correct class.
=> [jenkins] fix: update helper name

sdk/javascript/package-lock.json, sdk/javascript/package.json
[sdk/javascript]: mocha runner is being used but jest types are being used
problem: mismatch between test runner and types
solution: replace jest types with mocha types
[sdk/javascript]: refresh package-lock.json
problem: package-lock.json is stale
solution: regenerate it
=> [sdk/javascript]: mocha runner is being used but jest types are being used

.github/buildConfiguration.yaml, .github/jenkinsfile/mainnetBackupDual.groovy, .github/jenkinsfile/mainnetBackupPeer.groovy, jenkins/shared-library/vars/backupCatapultNodePipeline.groovy, jenkins/shared-library/vars/defaultCiPipeline.groovy, jenkins/shared-library/vars/helper.groovy
problem: no snapshot available for mainnet nodes
solution: add Jenkins job to create weekly backups of dual and peer nodes
=> [jenkins] feat: add Jenkins job to backup mainnet node

sdk/javascript/src/facade/SymbolFacade.js, sdk/javascript/test/facade/SymbolFacade_spec.js
problem: when calculating fee for aggregate transactions the total number of cosignatures needs to be taken into account
currently, this is not easy to configure via createTransactionFromTypedDescriptor
solution: add an optional cosignatureCount parameter
=> [sdk/javascript]: add cosignatureCount optional parameter to SymbolFacade createTransactionFromTypedDescriptor

sdk/javascript/src/facade/NemFacade.js, sdk/javascript/src/facade/SymbolFacade.js, sdk/javascript/test/facade/NemFacade_spec.js, sdk/javascript/test/facade/SymbolFacade_spec.js, sdk/python/symbolchain/facade/NemFacade.py, sdk/python/symbolchain/facade/SymbolFacade.py, sdk/python/tests/facade/test_NemFacade.py, sdk/python/tests/facade/test_SymbolFacade.py
problem: sdk user needs to interact with facade too much
solution: expand account class and add public account class
=> [sdk]: add public account and behaviors to account classes

.github/buildConfiguration.yaml, .github/jenkinsfile/cloneSymbolBranches.groovy, jenkins/shared-library/vars/cloneGitHubBranchesPipeline.groovy, jenkins/shared-library/vars/githubHelper.groovy
problem: currently have to manually sync GitHub branches
solution: add Jenkins pipeline to sync branches from one repo to another
=>  [jenkins] feat: clone github branches from one repo to another

client/rest/test/server/bootstrapper_spec.js
problem: async bootstrap tests are explicitly calling done
solution: return Promise instead
=> [client/rest]: convert bootstrap tests to return Promise

client/rest/src/plugins/rosetta/constructionRoutes.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/rosettaUtils_spec.js, client/rest/test/plugins/rosetta/rosetta_spec.js, client/rest/test/plugins/utils/pluginTestUtils.js
problem: add initial rosetta route with tests
solution: add construction/derive
=> [client/rest]: add construction/derive

client/rest/src/index.js, client/rest/src/plugins/rosetta/constructionRoutes.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/rosettaUtils_spec.js, client/rest/test/plugins/rosetta/rosetta_spec.js
problem: add additional rosetta routes and refactor to allow async routes
solution: add two more construction routes
=> [client/rest]: add construction/preprocess and construction/metadata

client/rest/src/plugins/rosetta/constructionRoutes.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/rosettaUtils_spec.js
1.    restructure rosetta error handling
problem: error path tests are broken and not all errors are mapped correctly
solution: create rosetta error wrapper that can be thrown and handled upstream
2.  update metadata to query network/fees/transaction (will be squashed)
=> [client/rest]: pair of fixes to WIP rosetta implementation

client/rest/src/plugins/rosetta/constructionRoutes.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/rosetta_spec.js
/construction/payloads
/construction/combine
/construction/parse
/construction/hash
/construction/submit
=> [client/rest]: add remaining construction apis

client/rest/src/plugins/rosetta/CatapultProxy.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/CatapultProxy_spec.js
(will be squashed into previous)
=> [client/rest]: add fetchAll to CatapultProxy

client/rest/src/plugins/rosetta/OperationParser.js, client/rest/src/plugins/rosetta/constructionRoutes.js, client/rest/test/plugins/rosetta/OperationParser_spec.js, client/rest/test/plugins/rosetta/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/utils/PayloadResultVerifier.js
problem: both construction and data routes need to parse transactions into operations
solution: refactor and extend logic in /parse
=> [client/rest]: extend and refactor transaction to operating parsing

client/rest/src/plugins/rosetta/OperationParser.js, client/rest/test/plugins/rosetta/OperationParser_spec.js
problem: mosaic supply changes need to be tracked
solution: add appropriate handling
=> [client/rest]: update OperationParser to support mosaic supply change and revocation

client/rest/src/plugins/rosetta/OperationParser.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/OperationParser_spec.js, client/rest/test/plugins/rosetta/rosettaUtils_spec.js
[client/rest]: filter out zero transfer operations
problem: zero transfer operations do not change state
solution: do not create zero transfer operations
[client/rest]: calculate transaction location in OperationParser and pass down to lookupCurrency
problem: transaction location is needed for proper mosaic alias resolution
solution: calculate it in OperationParser
=> [client/rest]: more rosetta integration changes 

client/rest/src/plugins/rosetta/CatapultProxy.js, client/rest/src/plugins/rosetta/OperationParser.js, client/rest/src/plugins/rosetta/constructionRoutes.js, client/rest/test/plugins/rosetta/CatapultProxy_spec.js, client/rest/test/plugins/rosetta/OperationParser_spec.js
problem: account balances cannot be calculated correctly without resolutions
solution: resolve addresses
=> [client/rest]: add address resolution support to rosetta routes

client/rest/src/plugins/rosetta/OperationParser.js, client/rest/src/plugins/rosetta/accountRoutes.js, client/rest/src/plugins/rosetta/blockRoutes.js, client/rest/src/plugins/rosetta/mempoolRoutes.js, client/rest/src/plugins/rosetta/networkRoutes.js, client/rest/src/plugins/rosetta/rosetta.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/accountRoutes_spec.js, client/rest/test/plugins/rosetta/blockRoutes_spec.js, client/rest/test/plugins/rosetta/mempoolRoutes_spec.js, client/rest/test/plugins/rosetta/networkRoutes_spec.js, client/rest/test/plugins/rosetta/rosetta_spec.js, client/rest/test/plugins/rosetta/utils/rosettaTestUtils.js
problem: Currently there is no Rosetta data endpoint
solution: Add Rosetta endpoint
=> [client/rest]: Rosetta data endpoints

client/rest/resources/rest.json, client/rest/src/index.js
problem: rosetta doesn't need specialized config
solution: remove rosetta config
=> [client/rosetta]: drop rest rosetta config

client/rest/src/plugins/rosetta/CatapultProxy.js, client/rest/src/plugins/rosetta/networkRoutes.js, client/rest/test/plugins/rosetta/CatapultProxy_spec.js, client/rest/test/plugins/rosetta/networkRoutes_spec.js
problem: curencyMosaicId alias resolutions are spamming REST server
solution: cache permanent namespace resolutions
fill cache exactly once in /network/status
=> [client/rest]: cache permanent namespace resolutions

client/rest/src/plugins/rosetta/accountRoutes.js, client/rest/test/plugins/rosetta/accountRoutes_spec.js
problem: user request to include mempool balance was not implemented
solution: implement mempool balance support for account
=> [client/rest]: add support to adjust account coins with mempool tx

client/rest/package.json, client/rest/resources/rest.rosetta.json, client/rest/src/index.js, client/rest/src/index.rosetta.js, client/rest/src/plugins/rosetta/rosetta.js, client/rest/src/server/process.js, client/rest/test/server/process_spec.js
problem: rosetta is bundled within catapult REST directly
solution: move rosetta implementation into new mini REST
=> [client/rest]: refactor most of process hosting into server/process

jenkins/docker/ubuntu/golang.Dockerfile, jenkins/infra/jenkins/build-ci-image-all.groovy, jenkins/infra/jenkins/build-ci-image.groovy
problem: currently there is no support for golang CI builds
solution: add infrastructure to build a golang CI image
=> [jenkins]: add golang ci image

jenkins/shared-library/vars/codeCoverage.groovy
problem: no code coverage support for golang
solution: add golang checks for code coverage minimum
=> [jenkins]: add support for golang code coverage

client/rest/src/plugins/rosetta/nem/NemProxy.js, client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/src/plugins/rosetta/nem/rosettaUtils.js, client/rest/test/plugins/rosetta/nem/NemProxy_spec.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js, client/rest/test/plugins/rosetta/nem/rosettaUtils_spec.js
problem: OperationParser needs to be initialized with a lookupCurrency function
solution: add a default implementation
cache mosaic properties
=> [client/rest]: add NEM createLookupCurrencyFunction

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/src/plugins/rosetta/nem/constructionRoutes.js, client/rest/src/plugins/rosetta/symbol/OperationParser.js, client/rest/src/plugins/rosetta/symbol/constructionRoutes.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js, client/rest/test/plugins/rosetta/nem/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/nem/rosetta_spec.js, client/rest/test/plugins/rosetta/nem/utils/PayloadResultVerifier.js, client/rest/test/plugins/rosetta/symbol/OperationParser_spec.js, client/rest/test/plugins/rosetta/symbol/constructionRoutes_spec.js
[client/rest]: complete NEM rosetta construction routes
problem: some NEM rosetta construction routes are missing
solution: add all missing routes
[client/rest]: small fixes + enhancements to Symbol rosetta implementation
problem: combine does not check signature_type
solution: add check
problem: parse supported types filter no longer makes sense with OperationParser
solution: remove filter
problem: prefer natural order wherever possible
solution: remove sort in account_identifier_signers
=>  [client/rest]: complete NEM rosetta construction routes

client/rest/src/plugins/rosetta/nem/networkRoutes.js, client/rest/src/plugins/rosetta/nem/rosetta.js, client/rest/test/plugins/rosetta/nem/networkRoutes_spec.js, client/rest/test/plugins/rosetta/nem/rosetta_spec.js
problem: no nem network routes
solution: add nem network routes
=> [client/rest]: add NEM network routes

client/rest/src/plugins/rosetta/nem/NemProxy.js, client/rest/src/plugins/rosetta/nem/accountRoutes.js, client/rest/src/plugins/rosetta/nem/rosetta.js, client/rest/src/plugins/rosetta/rosettaUtils.js, client/rest/test/plugins/rosetta/nem/NemProxy_spec.js, client/rest/test/plugins/rosetta/nem/accountRoutes_spec.js, client/rest/test/plugins/rosetta/nem/rosetta_spec.js, client/rest/test/plugins/rosetta/nem/utils/rosettaTestUtils.js, client/rest/test/plugins/rosetta/rosettaUtils_spec.js
problem: NEM is missing rosetta account routes
solution: add them
=> [client/rest]: add NEM rosetta account routes

client/rest/src/plugins/rosetta/nem/blockRoutes.js, client/rest/src/plugins/rosetta/nem/rosetta.js, client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js, client/rest/test/plugins/rosetta/nem/rosetta_spec.js
problem: no nem block routes
solution: add nem block routes
=> [client/rest]: add NEM block routes

sdk/javascript/src/index.js
problem: bytesToBigInt is exported but not bytesToInt
solution: export both
=> [sdk/javascript]: export bytesToInt via utils

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/src/plugins/rosetta/nem/blockRoutes.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js, client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js
problem: harvest fees are not extracted by rosetta
solution: add block transaction consisting of harvest fee
=> [client/rest]: NEM rosetta /block needs to create rosetta transaction for harvest fee

client/catapult/extensions/finalization/src/io/PrevoteChainStorage.h, client/catapult/extensions/finalization/src/model/FinalizationMessage.h, client/catapult/extensions/finalization/src/model/FinalizationMessageGroup.h, client/catapult/plugins/txes/restriction_account/src/state/AccountRestriction.h, client/catapult/tests/catapult/chain/ChainSynchronizerTests.cpp
> Note: This is the default pull request template.
> * Describe the current behavior of the application or program.
> * Please mention any related issue numbers.
remove repetitive words
> * Describe your changes in detail for the maintainer.
> * Explain the solution you have provided, and *how* it fixes the issue case.
> * Specify if this is a *breaking change*.
> * Were unit test cases or end-to-end test cases included in this fix, or was only manual testing applicable?
> * Please provide a detailed description of test cases included or updated.
> * Does this change introduce any new warnings or binding errors? If so, make sure to update the relevant documentation and reference this pull request.
---- 
> Your pull request must pass these requirements in order to be accepted. You can …
=> chore: remove repetitive words

sdk/javascript/generator_ts/AbstractTypeFormatter.py, sdk/javascript/scripts/ci/build.sh
problem: TS descriptor generator does not work
solution: fix it
add dryrun to build script
=> [sdk/javascript]: fix TS descriptor generator

client/rest/src/plugins/rosetta/nem/constructionRoutes.js, client/rest/test/plugins/rosetta/nem/constructionRoutes_spec.js, client/rest/test/plugins/rosetta/nem/utils/PayloadResultVerifier.js
[client/rest]: fix multisig transaction processing
problem: NEM multisig transaction processing is wrong
solution: fix multisig transaction construction
[client/rest]: fix multisig (outer) fee calculation
problem: multisig is using inner transaction fee
solution: use constant fee
=> [client/rest]: fix cosigning of NEM transactions in rosetta construction 

client/rest/src/plugins/rosetta/nem/constructionRoutes.js, client/rest/test/plugins/rosetta/nem/constructionRoutes_spec.js
problem: NEM requires public keys of addresses being added to multisig
solution: request public keys of addressAdditions in /preprocess
=> [client/rest]: request public keys for multisig address additions

client/rest/src/plugins/rosetta/nem/constructionRoutes.js, client/rest/test/plugins/rosetta/nem/constructionRoutes_spec.js
problem: NEM doesn't have concept of complete multisig and strips embedded multisig signatures
solution: submit multisig transaction and cosignatures separately
=> [client/rest]: fix /construction/submit for multisig transactions

client/rest/src/plugins/rosetta/nem/NemProxy.js, client/rest/test/plugins/rosetta/nem/NemProxy_spec.js, client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js, client/rest/test/plugins/rosetta/nem/utils/rosettaTestUtils.js
problem: rosetta implementation is unable to get information for expired mosaics
solution: use last (active or expired) mosaic definition for processing
=> [client/rest]: update NEM rosetta to use new /mosaic/definition/last api

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/src/plugins/rosetta/nem/accountRoutes.js, client/rest/src/plugins/rosetta/nem/blockRoutes.js, client/rest/src/plugins/rosetta/nem/mempoolRoutes.js, client/rest/src/plugins/rosetta/symbol/OperationParser.js, client/rest/src/plugins/rosetta/symbol/accountRoutes.js, client/rest/src/plugins/rosetta/symbol/blockRoutes.js, client/rest/src/plugins/rosetta/symbol/mempoolRoutes.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js, client/rest/test/plugins/rosetta/symbol/OperationParser_spec.js
problem: OperationParser is constructed same way in all online routes
solution: refactor creation in helper function (per blockchain)
=> [client/rest]: refactor creation of OperationParser

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/src/plugins/rosetta/nem/rosettaUtils.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js, client/rest/test/plugins/rosetta/nem/accountRoutes_spec.js, client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js, client/rest/test/plugins/rosetta/nem/rosettaUtils_spec.js
problem: OperationParser needs access to height when parsing mosaic definitions
solution: make OperationParser location aware (like Symbol)
=> [client/rest]: NEM OperationParser needs to be operation aware

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js, client/rest/test/plugins/rosetta/nem/blockRoutes_spec.js
problem: rosetta needs to be informed about expiring mosaics and zeroing of balances
solution: integrate new local/mosaics/expired NIS API
=> [client/rest]: query new NIS expired mosaics endpoint when processing blocks

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js
problem: NIS API has been modified to return restored mosaics and include expiredMosaicType flag in output
solution: check flag and credit or debit as appropriate
=> [client/rest]: update NEM rosetta to handle restored mosaics

client/rest/src/plugins/rosetta/nem/OperationParser.js, client/rest/test/plugins/rosetta/nem/OperationParser_spec.js
problem: parseBlock is undoing duplicate mosaic definitions assuming they are new mosaic definitions
solution: consider network state when determining amount to undo
=> [client/rest]: consider network state when undoing duplicate mosaic definitions in block

client/catapult/tests/catapult/io/PodIoUtilsTests.cpp, jenkins/catapult/compilers/clang-latest.yaml, jenkins/catapult/compilers/clang-prior.yaml, jenkins/catapult/runDockerTestsInnerTest.py
problem: not building with the latest version of Clang
solution: upgrade to Clang 19
=> [jenkins]: upgrade to clang 19

client/rest/package-lock.json, client/rest/package.json, sdk/javascript/package-lock.json, sdk/javascript/package.json
problem: mocha-jenkins-reporter tool seems to not be used
solution: remove mocha-jenkins-reporter from package.json
=> [monorepo] fix: remove the mocha-jenkins-reporter tool

client/rest/README_LIGHT.md
=> [client/rest]: Added light rest readme

catbuffer/parser/README.md, sdk/javascript/README.md, sdk/javascript/docs/typedoc.json, sdk/javascript/package-lock.json, sdk/javascript/package.json
This fixes building the SDK from scratch.
=> [sdk/javascript] fix: add build instructions and pin @types/node version

client/rest/README_LIGHT.md, client/rest/package.json, client/rest/resources/rest.light.json, client/rest/src/catapult-sdk/packet/PacketType.js, client/rest/src/index.light.js, client/rest/src/routes/light/chainRoutes.js, client/rest/src/routes/light/light.js, client/rest/src/routes/light/nodeRoutes.js, client/rest/src/sockets/chainInfoCodec.js, client/rest/src/sockets/finalizedBlockCodec.js, client/rest/test/routes/light/chainRoutes_spec.js, client/rest/test/routes/light/light_spec.js, client/rest/test/routes/light/nodeRoutes_spec.js, client/rest/test/sockets/chainInfoCodec_spec.js, client/rest/test/sockets/finalizedBlockCodec_spec.js
problem: users can not delegate harvesting via peer node.
solution: Added light rest implementation and endpoint
=> [client/rest]: implement light rest

jenkins/shared-library/vars/codeCoverage.groovy
problem: no Jacoco support for Gradle
solution: add Jacoco support for Gradle
=> [jenkins] fix: add support for Jacoco in Gradle

jenkins/docker/ubuntu/docs.Dockerfile, jenkins/infra/jenkins/build-ci-image-all.groovy, jenkins/infra/jenkins/build-ci-image.groovy
problem: no docker image for docs
solution: add Dockerfile for mkdocs project
=> [jenkins] fix: add docker image for docs
